const I18N={
 fr:{eyebrow:"VOTRE ESPACE · PLUSIEURS LABS",hero_title:"Votre parcours de psychiatrie, au même endroit.",hero_text:"Choisissez un Lab, reprenez exactement là où vous vous êtes arrêté et construisez progressivement votre profil clinique.",continue_bipolar:"Continuer BipolarLab",leaderboard:"Classements",axone_default:"« Un cours à la fois. Une compétence à la fois. »",dashboard_kicker:"TABLEAU DE BORD",psy_score:"PsyScore",courses_started:"Cours commencés",trophies:"Trophées",rank_global:"Rang général",cohort:"Promotion",labs_kicker:"MES LABS",labs_title:"Cours de psychiatrie",catalog_note:"Une plateforme, autant de cours que nécessaire.",architecture_kicker:"ARCHITECTURE V50",architecture_title:"Pensée pour grandir sans reconstruire le site.",arch_1:"Un seul compte et une seule authentification.",arch_2:"Une progression indépendante pour chaque cours.",arch_3:"Classements globaux, par cours et par promotion.",arch_4:"Interface prête pour FR / EN sans doubler les comptes.",account_title:"Compte & synchronisation",login:"Connexion",signup:"Créer un compte",profile:"Profil",password:"Mot de passe",pseudo:"Pseudonyme",cohort_optional:"Promotion / groupe (facultatif)",login_btn:"Se connecter",signup_btn:"Créer mon compte",save:"Enregistrer",logout:"Déconnexion",global:"Global",my_cohort:"Ma promotion",login_for_rank:"Connectez-vous pour afficher le classement.",rank_note:"Classement pédagogique, pseudonymisé et non certificatif.",your_path:"Votre parcours",start:"Commencer",continue:"Continuer",coming:"À venir",available:"Disponible",fr_ready:"FR disponible",en_ready:"EN disponible",en_later:"EN prévue",local:"Mode local"},
 en:{eyebrow:"YOUR SPACE · MULTIPLE LABS",hero_title:"Your psychiatry learning path, all in one place.",hero_text:"Choose a Lab, resume exactly where you stopped, and progressively build your clinical profile.",continue_bipolar:"Continue BipolarLab",leaderboard:"Leaderboards",axone_default:"“One course at a time. One skill at a time.”",dashboard_kicker:"DASHBOARD",psy_score:"PsyScore",courses_started:"Courses started",trophies:"Trophies",rank_global:"Global rank",cohort:"Cohort",labs_kicker:"MY LABS",labs_title:"Psychiatry courses",catalog_note:"One platform, as many courses as needed.",architecture_kicker:"V50 ARCHITECTURE",architecture_title:"Built to grow without rebuilding the website.",arch_1:"One account and one authentication system.",arch_2:"Independent progress for every course.",arch_3:"Global, course and cohort leaderboards.",arch_4:"FR / EN ready without duplicating user accounts.",account_title:"Account & sync",login:"Sign in",signup:"Create account",profile:"Profile",password:"Password",pseudo:"Username",cohort_optional:"Cohort / group (optional)",login_btn:"Sign in",signup_btn:"Create my account",save:"Save",logout:"Sign out",global:"Global",my_cohort:"My cohort",login_for_rank:"Sign in to view the leaderboard.",rank_note:"Educational, pseudonymous and non-certifying leaderboard.",your_path:"Your learning path",start:"Start",continue:"Continue",coming:"Coming soon",available:"Available",fr_ready:"FR available",en_ready:"EN available",en_later:"EN planned",local:"Local mode"}
};
let lang=localStorage.getItem('psylabLang')||'fr';
let client=null,user=null,profile=null,courseProgress=[];
const cfg=window.PSYLAB_CONFIG||{};
function t(k){return I18N[lang]?.[k]||I18N.fr[k]||k}
function setLang(next){lang=next==='en'?'en':'fr';localStorage.setItem('psylabLang',lang);document.documentElement.lang=lang;document.querySelectorAll('[data-lang]').forEach(b=>b.classList.toggle('active',b.dataset.lang===lang));document.querySelectorAll('[data-i18n]').forEach(el=>{const k=el.dataset.i18n;if(I18N[lang]?.[k])el.textContent=I18N[lang][k]});document.querySelectorAll('[data-i18n-label]').forEach(el=>{const k=el.dataset.i18nLabel;const input=el.querySelector('input');const label=t(k);if(input){[...el.childNodes].filter(n=>n.nodeType===3).forEach(n=>n.remove());el.insertBefore(document.createTextNode(label),input)}});renderCourses();renderIdentity()}
function localBipolarMetrics(){try{const s=JSON.parse(localStorage.getItem('bplabV40')||'{}'),n=JSON.parse(localStorage.getItem('bplabN2V44')||'{}');const vals=o=>Object.values(o||{}),dis=vals(s.levels).filter(v=>Number(v)>=2).length,mem=vals(s.memory).filter(v=>v==='solid').length,duels=vals(s.duels).filter(Boolean).length,rev=vals(s.v43?.reverse).filter(v=>v==='solid').length,rep=vals(s.v43?.repair).filter(v=>v==='solid').length,boss=Math.max(0,Math.min(10,Number(s.v43?.boss||0))),n1=Math.min(1000,Math.round(dis/50*350+mem/50*300+Math.min(duels,30)/30*150+Math.min(rev+rep,16)/16*100+boss/10*100));const st=vals(n.stations).filter(v=>v==='acquis').length,comp=vals(n.comp).filter(v=>v==='acquis').length,staff=vals(n.staffEval).filter(v=>v==='acquis').length;let cockpit=0;Object.values(n.cockpit||{}).forEach(x=>Object.values(x||{}).forEach(v=>{if(v===true)cockpit++}));const n2=Math.min(1000,Math.round(st/30*350+comp/11*250+Math.min(cockpit,24)/24*200+(n.boss==='acquis'?100:0)+Math.min(staff,8)/8*100));const score=Math.round(n1*.45+n2*.55),trophies=vals(s.v48?.trophies).filter(Boolean).length;return{course_key:'bipolar',course_score:score,level_scores:{n1,n2},trophy_count:trophies,local:true}}catch(e){return{course_key:'bipolar',course_score:0,level_scores:{n1:0,n2:0},trophy_count:0,local:true}}}
function progressFor(key){return courseProgress.find(x=>x.course_key===key)||(key==='bipolar'?localBipolarMetrics():null)}
function renderCourses(){const grid=document.getElementById('courseGrid');if(!grid)return;grid.innerHTML=(window.PSYLAB_COURSES||[]).map(c=>{const p=progressFor(c.key),score=Number(p?.course_score||0),pct=Math.round(score/10),active=c.status==='active',title=lang==='en'?c.title_en:c.title_fr,sub=lang==='en'?c.subtitle_en:c.subtitle_fr,desc=lang==='en'?c.description_en:c.description_fr,levels=(c.levels||[]).map(l=>'<span>'+escapeHtml(lang==='en'?l.en:l.fr)+'</span>').join(''),langs=(c.languages||[]).map(x=>'<span class="ready">'+x.toUpperCase()+'</span>').join('')+(c.key==='bipolar'&&!c.languages.includes('en')?'<span>'+t('en_later')+'</span>':'');return `<article class="course-card ${active?'active-course':''}"><div class="course-status ${active?'live':''}">${active?t('available'):t('coming')}</div><div class="course-icon">${escapeHtml(c.icon)}</div><h3>${escapeHtml(title)}</h3><div class="course-subtitle">${escapeHtml(sub)}</div><p class="course-description">${escapeHtml(desc)}</p><div class="level-list">${levels}</div><div class="language-badges">${langs}</div><div class="course-progress"><i style="width:${pct}%"></i></div><div class="course-progress-label">${score} / 1000 · ${pct}%</div><div class="course-action">${active?`<a href="${c.href}">${score>0?t('continue'):t('start')}</a>`:`<button disabled>${t('coming')}</button>`}</div></article>`}).join('');renderStats()}
function renderStats(){const all=courseProgress.length?courseProgress:[localBipolarMetrics()];const started=all.filter(x=>Number(x.course_score)>0).length,total=all.reduce((a,x)=>a+Number(x.course_score||0),0),trophies=all.reduce((a,x)=>a+Number(x.trophy_count||0),0);setText('coursesStarted',started);setText('totalTrophies',trophies);setText('globalScore',total||0);setText('cohortStat',profile?.cohort_code||'—')}
function setText(id,v){const el=document.getElementById(id);if(el)el.textContent=v}
function renderIdentity(){const label=document.getElementById('accountLabel'),chip=document.getElementById('accountChip'),welcome=document.getElementById('welcomeTitle');if(user){const name=profile?.display_name||user.user_metadata?.display_name||'Resident';label.textContent=name;chip.classList.add('online');welcome.textContent=(lang==='fr'?'Bonjour ':'Welcome ')+name;setText('profileName',name);setText('profileEmail',user.email||'—');const pp=document.getElementById('profilePseudo');if(pp)pp.value=name;const pc=document.getElementById('profileCohort');if(pc)pc.value=profile?.cohort_code||''}else{label.textContent=t('local');chip.classList.remove('online');welcome.textContent=t('your_path');setText('profileName',t('local'));setText('profileEmail','—')}renderStats()}
function openModal(id){document.getElementById(id)?.classList.add('show');document.getElementById(id)?.setAttribute('aria-hidden','false')}
function closeModal(id){document.getElementById(id)?.classList.remove('show');document.getElementById(id)?.setAttribute('aria-hidden','true')}
function showPane(name){document.querySelectorAll('[data-pane]').forEach(x=>x.classList.toggle('active',x.dataset.pane===name));document.querySelectorAll('[data-pane-btn]').forEach(x=>x.classList.toggle('active',x.dataset.paneBtn===name))}
function message(txt,type=''){const el=document.getElementById('cloudMessage');if(!el)return;el.textContent=txt;el.className='cloud-message '+type}
function configured(){return String(cfg.url||'').length>10&&String(cfg.anonKey||cfg.publishableKey||'').length>20}
function gateMessage(txt,type=''){const el=document.getElementById('gateMessage');if(!el)return;el.textContent=txt;el.className='gate-message '+type}
function showGatePane(name){document.querySelectorAll('[data-gate-pane]').forEach(x=>x.classList.toggle('active',x.dataset.gatePane===name));document.querySelectorAll('[data-gate-pane-btn]').forEach(x=>x.classList.toggle('active',x.dataset.gatePaneBtn===name))}
function setAuthUI(authenticated){document.body.classList.toggle('authenticated',!!authenticated);document.body.classList.toggle('auth-locked',!authenticated);if(authenticated){gateMessage(lang==='fr'?'Connexion établie. Ouverture de votre espace…':'Signed in. Opening your workspace…','good')}}
async function initCloud(){
 setAuthUI(false);
 if(!configured()){
   message(lang==='fr'?'Configuration Supabase requise pour activer PsyLab.':'Supabase configuration is required to activate PsyLab.','bad');
   gateMessage(lang==='fr'?'PsyLab n’est pas encore relié à Supabase. L’inscription sera disponible après la configuration.':'PsyLab is not connected to Supabase yet. Registration will be available after setup.','bad');
   document.querySelectorAll('#gateSignupBtn,#gateLoginBtn').forEach(b=>b.disabled=true);
   renderIdentity();return
 }
 if(!window.supabase?.createClient){gateMessage(lang==='fr'?'Service de connexion indisponible. Réessayez dans un instant.':'Sign-in service unavailable. Please try again.','bad');return}
 client=window.supabase.createClient(cfg.url,cfg.anonKey||cfg.publishableKey,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});
 const {data,error}=await client.auth.getSession();
 if(error){gateMessage(error.message,'bad');return}
 user=data.session?.user||null;
 client.auth.onAuthStateChange(async(_,session)=>{
   user=session?.user||null;
   setAuthUI(!!user);
   if(user){await loadProfile();await loadProgress();await loadMyGlobalRank();closeModal('accountModal')}
   else{profile=null;courseProgress=[];renderCourses();renderIdentity();showGatePane('login')}
 });
 if(user){setAuthUI(true);await loadProfile();await loadProgress();await loadMyGlobalRank()}else{setAuthUI(false);gateMessage(lang==='fr'?'Créez votre compte ou connectez-vous pour accéder aux Labs.':'Create an account or sign in to access the Labs.')}
 renderIdentity()
}
async function loadProfile(){if(!user)return;let {data,error}=await client.from('profiles').select('display_name,cohort_code').eq('id',user.id).maybeSingle();if(error){message(error.message,'bad');return}profile=data||null;renderIdentity()}
async function loadProgress(){if(!user)return;const {data,error}=await client.from('course_progress').select('course_key,course_score,level_scores,trophy_count,updated_at').eq('user_id',user.id);if(error){message(error.message,'bad');return}courseProgress=data||[];renderCourses()}
async function login(){if(!client){message(lang==='fr'?'Configurez Supabase avant la connexion.':'Configure Supabase before signing in.','bad');return}const email=document.getElementById('loginEmail').value.trim(),password=document.getElementById('loginPassword').value;message(lang==='fr'?'Connexion…':'Signing in…');const {error}=await client.auth.signInWithPassword({email,password});if(error)message(error.message,'bad');else message(lang==='fr'?'Connecté.':'Signed in.','good')}
async function signup(){if(!client){message(lang==='fr'?'Configurez Supabase avant la création de compte.':'Configure Supabase first.','bad');return}const display_name=document.getElementById('signupPseudo').value.trim(),cohort_code=document.getElementById('signupCohort').value.trim().toUpperCase(),email=document.getElementById('signupEmail').value.trim(),password=document.getElementById('signupPassword').value;if(display_name.length<3){message(lang==='fr'?'Pseudonyme : 3 caractères minimum.':'Username: at least 3 characters.','bad');return}if(password.length<8){message(lang==='fr'?'Mot de passe : 8 caractères minimum.':'Password: at least 8 characters.','bad');return}const {data,error}=await client.auth.signUp({email,password,options:{data:{display_name,cohort_code}}});if(error)message(error.message,'bad');else message(data.session?(lang==='fr'?'Compte créé.':'Account created.'):(lang==='fr'?'Compte créé. Vérifiez votre e-mail si la confirmation est activée.':'Account created. Check your email if confirmation is enabled.'),'good')}
async function gateLogin(){
 if(!client){gateMessage(lang==='fr'?'PsyLab n’est pas encore configuré.':'PsyLab is not configured yet.','bad');return}
 const email=document.getElementById('gateLoginEmail').value.trim(),password=document.getElementById('gateLoginPassword').value;
 if(!email||!password){gateMessage(lang==='fr'?'Renseignez votre e-mail et votre mot de passe.':'Enter your email and password.','bad');return}
 gateMessage(lang==='fr'?'Connexion…':'Signing in…');
 const {error}=await client.auth.signInWithPassword({email,password});if(error)gateMessage(error.message,'bad')
}
async function gateSignup(){
 if(!client){gateMessage(lang==='fr'?'PsyLab n’est pas encore configuré.':'PsyLab is not configured yet.','bad');return}
 const display_name=document.getElementById('gateSignupPseudo').value.trim(),cohort_code=document.getElementById('gateSignupCohort').value.trim().toUpperCase(),email=document.getElementById('gateSignupEmail').value.trim(),password=document.getElementById('gateSignupPassword').value;
 if(display_name.length<3){gateMessage(lang==='fr'?'Pseudonyme : 3 caractères minimum.':'Username: at least 3 characters.','bad');return}
 if(!email){gateMessage(lang==='fr'?'Renseignez une adresse e-mail.':'Enter an email address.','bad');return}
 if(password.length<8){gateMessage(lang==='fr'?'Mot de passe : 8 caractères minimum.':'Password: at least 8 characters.','bad');return}
 gateMessage(lang==='fr'?'Création du compte…':'Creating account…');
 const {data,error}=await client.auth.signUp({email,password,options:{data:{display_name,cohort_code}}});
 if(error){gateMessage(error.message,'bad');return}
 if(data.session){gateMessage(lang==='fr'?'Compte créé. Ouverture de PsyLab…':'Account created. Opening PsyLab…','good')}
 else{gateMessage(lang==='fr'?'Compte créé. Vérifiez votre e-mail puis revenez vous connecter.':'Account created. Check your email, then return to sign in.','good');showGatePane('login')}
}
async function saveProfile(){if(!client||!user)return;const display_name=document.getElementById('profilePseudo').value.trim(),cohort_code=document.getElementById('profileCohort').value.trim().toUpperCase()||null;const {data,error}=await client.from('profiles').update({display_name,cohort_code,updated_at:new Date().toISOString()}).eq('id',user.id).select('display_name,cohort_code').single();if(error)message(error.message,'bad');else{profile=data;message(lang==='fr'?'Profil enregistré.':'Profile saved.','good');renderIdentity()}}
async function logout(){if(client)await client.auth.signOut();closeModal('accountModal');setAuthUI(false);showGatePane('login');window.scrollTo({top:0,behavior:'smooth'})}
async function loadMyGlobalRank(){if(!client||!user)return;const {data,error}=await client.rpc('get_platform_leaderboard',{p_cohort:null,p_limit:200});if(error)return;const me=(data||[]).find(x=>x.user_id===user.id);setText('globalRank',me?'#'+me.rank:'—')}
async function loadLeaderboard(mode='global'){const box=document.getElementById('leaderboardBox');document.querySelectorAll('[data-leader]').forEach(b=>b.classList.toggle('active',b.dataset.leader===mode));if(!user||!client){box.innerHTML='<div class="empty-state">'+t('login_for_rank')+'</div>';return}box.innerHTML='<div class="empty-state">…</div>';let data,error;if(mode==='bipolar'){({data,error}=await client.rpc('get_course_leaderboard',{p_course_key:'bipolar',p_level_key:null,p_cohort:null,p_limit:100}))}else{const cohort=mode==='cohort'?(profile?.cohort_code||null):null;if(mode==='cohort'&&!cohort){box.innerHTML='<div class="empty-state">'+(lang==='fr'?'Ajoutez une promotion à votre profil.':'Add a cohort to your profile.')+'</div>';return}({data,error}=await client.rpc('get_platform_leaderboard',{p_cohort:cohort,p_limit:100}))}if(error){box.innerHTML='<div class="empty-state">'+escapeHtml(error.message)+'</div>';return}renderLeaderboard(data||[],mode)}
function renderLeaderboard(rows,mode){const box=document.getElementById('leaderboardBox');if(!rows.length){box.innerHTML='<div class="empty-state">'+(lang==='fr'?'Aucun score pour le moment.':'No scores yet.')+'</div>';return}const isCourse=mode==='bipolar';box.innerHTML='<div class="leader-row head"><span>#</span><span>'+(lang==='fr'?'Résident':'Resident')+'</span><span>'+(isCourse?'Score':'PsyScore')+'</span><span>'+(lang==='fr'?'Trophées':'Trophies')+'</span></div>'+rows.map(r=>`<div class="leader-row ${r.user_id===user?.id?'me':''}"><div class="leader-rank">#${r.rank}</div><div class="leader-name"><b>${escapeHtml(r.display_name)}${r.user_id===user?.id?' · '+(lang==='fr'?'Vous':'You'):''}</b><small>${escapeHtml(r.cohort_code||'')}</small></div><div class="leader-score">${Number(isCourse?r.course_score:r.total_score||0)}</div><div>${Number(r.trophy_count||r.total_trophies||0)}</div></div>`).join('')}
function escapeHtml(v){return String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}

document.querySelectorAll('[data-lang]').forEach(b=>b.addEventListener('click',()=>setLang(b.dataset.lang)));
document.getElementById('accountChip').addEventListener('click',()=>{openModal('accountModal');showPane(user?'profile':'login')});
document.getElementById('openLeaderboard').addEventListener('click',()=>{openModal('leaderboardModal');loadLeaderboard('global')});
document.querySelectorAll('[data-close]').forEach(b=>b.addEventListener('click',()=>closeModal(b.dataset.close)));
document.querySelectorAll('.modal-backdrop').forEach(m=>m.addEventListener('click',e=>{if(e.target===m)closeModal(m.id)}));
document.querySelectorAll('[data-pane-btn]').forEach(b=>b.addEventListener('click',()=>showPane(b.dataset.paneBtn)));
document.querySelectorAll('[data-leader]').forEach(b=>b.addEventListener('click',()=>loadLeaderboard(b.dataset.leader)));
document.getElementById('loginBtn').addEventListener('click',login);document.getElementById('signupBtn').addEventListener('click',signup);document.getElementById('saveProfileBtn').addEventListener('click',saveProfile);document.getElementById('logoutBtn').addEventListener('click',logout);
document.querySelectorAll('[data-gate-pane-btn]').forEach(b=>b.addEventListener('click',()=>showGatePane(b.dataset.gatePaneBtn)));
document.getElementById('gateLoginBtn')?.addEventListener('click',gateLogin);document.getElementById('gateSignupBtn')?.addEventListener('click',gateSignup);
document.getElementById('gateLoginPassword')?.addEventListener('keydown',e=>{if(e.key==='Enter')gateLogin()});document.getElementById('gateSignupPassword')?.addEventListener('keydown',e=>{if(e.key==='Enter')gateSignup()});
setLang(lang);renderCourses();initCloud();
