(function(){
const cfg=window.PSYLAB_CONFIG||{},key=cfg.anonKey||cfg.publishableKey||'';let client=null,user=null,profile=null,progress=[];
const q=s=>document.querySelector(s),qa=s=>[...document.querySelectorAll(s)];
function msg(t,type=''){const e=q('#authMessage');if(!e)return;e.textContent=t;e.className='ps59-auth-message '+type}
function setPane(name){qa('[data-auth-tab]').forEach(b=>b.classList.toggle('active',b.dataset.authTab===name));qa('[data-auth-pane]').forEach(p=>p.classList.toggle('active',p.dataset.authPane===name))}
async function loadContext(){if(!user)return;let r=await client.from('profiles').select('display_name,cohort_code,avatar_path,show_avatar_public,residency_year,preferred_language').eq('id',user.id).maybeSingle();profile=r.data||{};if(profile.preferred_language&&!localStorage.getItem('psylab_lang_v59')){localStorage.setItem('psylab_lang_v59',profile.preferred_language==='en'?'en':'fr')}let p=await client.from('course_progress').select('course_key,course_score,level_scores,trophy_count,updated_at').eq('user_id',user.id);progress=p.data||[];window.PSYLAB_V59_CONTEXT={client,user,profile,progress};document.body.classList.remove('ps59-auth-pending','ps59-auth-required');document.body.classList.add('ps59-authenticated');window.dispatchEvent(new CustomEvent('psylab:v59-ready',{detail:window.PSYLAB_V59_CONTEXT}));const next=new URLSearchParams(location.search).get('next');if(next&&next.startsWith('/')&&!sessionStorage.getItem('v59-next-used')){sessionStorage.setItem('v59-next-used','1');location.replace(next)}}
async function init(){if(!cfg.url||!key||!window.supabase?.createClient){document.body.classList.remove('ps59-auth-pending');document.body.classList.add('ps59-auth-required');msg('Configuration Supabase requise.','bad');return}client=window.supabase.createClient(cfg.url,key,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});const {data,error}=await client.auth.getSession();if(error){document.body.classList.remove('ps59-auth-pending');document.body.classList.add('ps59-auth-required');msg(error.message,'bad');return}user=data.session?.user||null;if(user)await loadContext();else{document.body.classList.remove('ps59-auth-pending');document.body.classList.add('ps59-auth-required')}client.auth.onAuthStateChange(async(_,s)=>{user=s?.user||null;if(user)await loadContext();else{document.body.classList.remove('ps59-authenticated','ps59-auth-pending');document.body.classList.add('ps59-auth-required');profile=null;progress=[];window.PSYLAB_V59_CONTEXT=null}})}
async function login(){const email=q('#loginEmail')?.value.trim(),password=q('#loginPassword')?.value;if(!email||!password){msg(window.PsyLabV59?.lang()==='en'?'Enter your email and password.':'Renseignez votre e-mail et votre mot de passe.','bad');return}msg(window.PsyLabV59?.lang()==='en'?'Signing in…':'Connexion…');const {error}=await client.auth.signInWithPassword({email,password});if(error)msg(error.message,'bad')}
async function signup(){const display_name=q('#signupPseudo')?.value.trim(),residency_year=q('#signupYear')?.value||null,cohort_code=(q('#signupCohort')?.value||'').trim().toUpperCase(),email=q('#signupEmail')?.value.trim(),password=q('#signupPassword')?.value||'';if(display_name.length<3){msg(window.PsyLabV59?.lang()==='en'?'Nickname: at least 3 characters.':'Pseudonyme : 3 caractères minimum.','bad');return}if(password.length<8){msg(window.PsyLabV59?.lang()==='en'?'Password: at least 8 characters.':'Mot de passe : 8 caractères minimum.','bad');return}msg(window.PsyLabV59?.lang()==='en'?'Creating account…':'Création du compte…');const preferred_language=window.PsyLabV59?.lang?.()||'fr';const {data,error}=await client.auth.signUp({email,password,options:{data:{display_name,cohort_code,residency_year,preferred_language},emailRedirectTo:location.origin}});if(error){msg(error.message,'bad');return}if(data.session)msg(preferred_language==='en'?'Account created. Opening PsyLab…':'Compte créé. Ouverture de PsyLab…','good');else{msg(preferred_language==='en'?'Account created. Check your email, then sign in.':'Compte créé. Vérifiez votre e-mail puis connectez-vous.','good');setPane('login')}}
qa('[data-auth-tab]').forEach(b=>b.onclick=()=>setPane(b.dataset.authTab));q('#loginBtn')?.addEventListener('click',login);q('#signupBtn')?.addEventListener('click',signup);q('#loginPassword')?.addEventListener('keydown',e=>{if(e.key==='Enter')login()});q('#signupPassword')?.addEventListener('keydown',e=>{if(e.key==='Enter')signup()});
window.PsyLabAuthV59={logout:async()=>{if(client)await client.auth.signOut();location.replace('index.html')}};
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();
