(function(){
const cfg=window.PSYLAB_CONFIG||{},key=cfg.anonKey||cfg.publishableKey||'';let client=null,user=null,profile=null,progress=[];
const q=s=>document.querySelector(s),qa=s=>[...document.querySelectorAll(s)];
function msg(t,type=''){const e=q('#v57AuthMessage');if(!e)return;e.textContent=t;e.className='v57-auth-message '+type}
function setPane(name){qa('[data-v57-auth-tab]').forEach(b=>b.classList.toggle('active',b.dataset.v57AuthTab===name));qa('[data-v57-auth-pane]').forEach(p=>p.classList.toggle('active',p.dataset.v57AuthPane===name))}
async function loadContext(){if(!user)return;let r=await client.from('profiles').select('display_name,cohort_code,avatar_path,show_avatar_public,residency_year,preferred_language').eq('id',user.id).maybeSingle();profile=r.data||{};let p=await client.from('course_progress').select('course_key,course_score,level_scores,trophy_count,updated_at').eq('user_id',user.id);progress=p.data||[];window.PSYLAB_V57_CONTEXT={client,user,profile,progress};document.body.classList.add('v57-authenticated');window.dispatchEvent(new CustomEvent('psylab:v57-ready',{detail:window.PSYLAB_V57_CONTEXT}));const next=new URLSearchParams(location.search).get('next');if(next&&next.startsWith('/')&&!sessionStorage.getItem('v57-next-used')){sessionStorage.setItem('v57-next-used','1');location.replace(next)}}
async function init(){if(!cfg.url||!key||!window.supabase?.createClient){msg('Configuration Supabase requise.','bad');qa('.v57-auth-pane button').forEach(b=>b.disabled=true);return}client=window.supabase.createClient(cfg.url,key,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});const {data,error}=await client.auth.getSession();if(error){msg(error.message,'bad');return}user=data.session?.user||null;if(user)await loadContext();client.auth.onAuthStateChange(async(_,s)=>{user=s?.user||null;if(user)await loadContext();else{document.body.classList.remove('v57-authenticated');profile=null;progress=[];window.PSYLAB_V57_CONTEXT=null}})}
async function login(){const email=q('#v57LoginEmail').value.trim(),password=q('#v57LoginPassword').value;if(!email||!password){msg('Renseignez votre e-mail et votre mot de passe.','bad');return}msg('Connexion…');const {error}=await client.auth.signInWithPassword({email,password});if(error)msg(error.message,'bad')}
async function signup(){const display_name=q('#v57SignupPseudo').value.trim(),residency_year=q('#v57SignupYear').value||null,cohort_code=q('#v57SignupCohort').value.trim().toUpperCase(),email=q('#v57SignupEmail').value.trim(),password=q('#v57SignupPassword').value;if(display_name.length<3){msg('Pseudonyme : 3 caractères minimum.','bad');return}if(password.length<8){msg('Mot de passe : 8 caractères minimum.','bad');return}msg('Création du compte…');const {data,error}=await client.auth.signUp({email,password,options:{data:{display_name,cohort_code,residency_year,preferred_language:'fr'},emailRedirectTo:location.origin}});if(error){msg(error.message,'bad');return}if(data.session)msg('Compte créé. Ouverture de PsyLab…','good');else{msg('Compte créé. Vérifiez votre e-mail puis connectez-vous.','good');setPane('login')}}
qa('[data-v57-auth-tab]').forEach(b=>b.onclick=()=>setPane(b.dataset.v57AuthTab));q('#v57LoginBtn')?.addEventListener('click',login);q('#v57SignupBtn')?.addEventListener('click',signup);q('#v57LoginPassword')?.addEventListener('keydown',e=>{if(e.key==='Enter')login()});q('#v57SignupPassword')?.addEventListener('keydown',e=>{if(e.key==='Enter')signup()});
window.PsyLabAuthV57={logout:async()=>{if(client)await client.auth.signOut();location.replace('index.html')}};
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();
