(function(){
const cfg=window.PSYLAB_CONFIG||{},key=cfg.anonKey||cfg.publishableKey||'';let client=null,user=null,profile=null,progress=[];
const q=s=>document.querySelector(s),qa=s=>[...document.querySelectorAll(s)];
function msg(t,type=''){const e=q('#authMessage');if(!e)return;e.textContent=t;e.className='ps59-auth-message '+type}
function setPane(name){qa('[data-auth-tab]').forEach(b=>b.classList.toggle('active',b.dataset.authTab===name));qa('[data-auth-pane]').forEach(p=>p.classList.toggle('active',p.dataset.authPane===name))}
function inferredName(){return user?.user_metadata?.display_name||user?.user_metadata?.full_name||user?.user_metadata?.name||user?.email?.split('@')[0]||''}
async function readProfile(){let r=await client.from('profiles').select('display_name,cohort_code,avatar_path,show_avatar_public,residency_year,professional_status,preferred_language').eq('id',user.id).maybeSingle();if(r.error){const fb=await client.from('profiles').select('display_name,cohort_code,avatar_path,show_avatar_public,residency_year,preferred_language').eq('id',user.id).maybeSingle();r={data:fb.data||{},error:fb.error};if(r.data&&!r.data.professional_status)r.data.professional_status=r.data.residency_year||null}return r}
function needsOnboarding(p){return !p?.professional_status}
function showOnboarding(){const wrap=q('#professionalOnboarding');if(!wrap)return;const n=inferredName();q('#onboardingPseudo').value=(profile?.display_name&&!/^Resident_/i.test(profile.display_name)?profile.display_name:n)||'';q('#onboardingStatus').value=profile?.professional_status||profile?.residency_year||'';wrap.hidden=false;document.body.classList.add('ps60-onboarding-open')}
async function completeOnboarding(){const display_name=q('#onboardingPseudo').value.trim(),professional_status=q('#onboardingStatus').value;if(display_name.length<2||!professional_status){q('#onboardingMessage').textContent=window.PsyLabV60.lang()==='en'?'Choose a nickname and your current professional status.':'Choisissez un pseudonyme et votre statut professionnel actuel.';return}const residency_year=/^R[1-4]$/.test(professional_status)?professional_status:null;const {error}=await client.from('profiles').update({display_name,professional_status,residency_year,preferred_language:window.PsyLabV60.lang(),updated_at:new Date().toISOString()}).eq('id',user.id);if(error){q('#onboardingMessage').textContent=error.message;return}q('#professionalOnboarding').hidden=true;document.body.classList.remove('ps60-onboarding-open');await loadContext(true)}
async function loadContext(skipOnboarding=false){if(!user)return;const r=await readProfile();profile=r.data||{};if(profile.preferred_language&&!localStorage.getItem('psylab_lang_v59'))localStorage.setItem('psylab_lang_v59',profile.preferred_language==='en'?'en':'fr');let p=await client.from('course_progress').select('course_key,course_score,level_scores,trophy_count,updated_at').eq('user_id',user.id);progress=p.data||[];window.PSYLAB_V60_CONTEXT={client,user,profile,progress};window.PSYLAB_V59_CONTEXT=window.PSYLAB_V60_CONTEXT;document.body.classList.remove('ps59-auth-pending','ps59-auth-required');document.body.classList.add('ps59-authenticated');if(needsOnboarding(profile)&&!skipOnboarding)showOnboarding();window.dispatchEvent(new CustomEvent('psylab:v59-ready',{detail:window.PSYLAB_V60_CONTEXT}));window.dispatchEvent(new CustomEvent('psylab:v60-ready',{detail:window.PSYLAB_V60_CONTEXT}));const next=new URLSearchParams(location.search).get('next');if(next&&next.startsWith('/')&&!sessionStorage.getItem('v60-next-used')&&!needsOnboarding(profile)){sessionStorage.setItem('v60-next-used','1');location.replace(next)}}
async function init(){if(!cfg.url||!key||!window.supabase?.createClient){document.body.classList.remove('ps59-auth-pending');document.body.classList.add('ps59-auth-required');msg('Configuration Supabase requise.','bad');return}client=window.supabase.createClient(cfg.url,key,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});const {data,error}=await client.auth.getSession();if(error){document.body.classList.remove('ps59-auth-pending');document.body.classList.add('ps59-auth-required');msg(error.message,'bad');return}user=data.session?.user||null;if(user)await loadContext();else{document.body.classList.remove('ps59-auth-pending');document.body.classList.add('ps59-auth-required')}client.auth.onAuthStateChange(async(_,s)=>{user=s?.user||null;if(user)await loadContext();else{document.body.classList.remove('ps59-authenticated','ps59-auth-pending');document.body.classList.add('ps59-auth-required');profile=null;progress=[];window.PSYLAB_V60_CONTEXT=null;window.PSYLAB_V59_CONTEXT=null}})}
async function login(){const email=q('#loginEmail')?.value.trim(),password=q('#loginPassword')?.value;if(!email||!password){msg(window.PsyLabV60.lang()==='en'?'Enter your email and password.':'Renseignez votre e-mail et votre mot de passe.','bad');return}msg(window.PsyLabV60.lang()==='en'?'Signing in…':'Connexion…');const {error}=await client.auth.signInWithPassword({email,password});if(error)msg(error.message,'bad')}
async function signup(){const email=q('#signupEmail')?.value.trim(),password=q('#signupPassword')?.value||'';if(!email){msg(window.PsyLabV60.lang()==='en'?'Enter your email address.':'Renseignez votre adresse e-mail.','bad');return}if(password.length<8){msg(window.PsyLabV60.lang()==='en'?'Password: at least 8 characters.':'Mot de passe : 8 caractères minimum.','bad');return}msg(window.PsyLabV60.lang()==='en'?'Creating account…':'Création du compte…');const preferred_language=window.PsyLabV60.lang();const {data,error}=await client.auth.signUp({email,password,options:{data:{preferred_language},emailRedirectTo:location.origin+location.pathname}});if(error){msg(error.message,'bad');return}if(data.session)msg(preferred_language==='en'?'Account created. Complete your profile to enter PsyLab.':'Compte créé. Complétez votre profil pour entrer dans PsyLab.','good');else{msg(preferred_language==='en'?'Account created. Check your email, then sign in.':'Compte créé. Vérifiez votre e-mail puis connectez-vous.','good');setPane('login')}}
async function oauth(provider){if(!client)return;msg(window.PsyLabV60.lang()==='en'?`Opening ${provider==='google'?'Google':'Apple'}…`:`Ouverture de ${provider==='google'?'Google':'Apple'}…`);const {error}=await client.auth.signInWithOAuth({provider,options:{redirectTo:location.origin+location.pathname}});if(error)msg(error.message,'bad')}
qa('[data-auth-tab]').forEach(b=>b.onclick=()=>setPane(b.dataset.authTab));qa('[data-oauth]').forEach(b=>b.onclick=()=>oauth(b.dataset.oauth));q('#loginBtn')?.addEventListener('click',login);q('#signupBtn')?.addEventListener('click',signup);q('#onboardingSave')?.addEventListener('click',completeOnboarding);q('#loginPassword')?.addEventListener('keydown',e=>{if(e.key==='Enter')login()});q('#signupPassword')?.addEventListener('keydown',e=>{if(e.key==='Enter')signup()});
window.PsyLabAuthV60={logout:async()=>{if(client)await client.auth.signOut();location.replace('index.html')}};window.PsyLabAuthV59=window.PsyLabAuthV60;
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();
