(function(){
const q=s=>document.querySelector(s),qa=s=>[...document.querySelectorAll(s)];
function compact(v,lang){v=String(v||'').toUpperCase();if(/^R[1-4]$/.test(v))return v;const fr={EXTERNE:'Externe',INTERNE:'Interne',ASSISTANT:'Assistant',PROFESSEUR:'Professeur'},en={EXTERNE:'Extern',INTERNE:'Intern',ASSISTANT:'Assistant',PROFESSEUR:'Professor'};return (lang==='en'?en:fr)[v]||v}
window.addEventListener('psylab:v60-page-ready',async e=>{const {client:c,user,profile}=e.detail,lang=window.PsyLabV60.lang();qa('[data-user-sub]').forEach(x=>x.textContent=compact(profile?.professional_status||profile?.residency_year,lang));try{const cur=await c.rpc('get_current_challenge',{p_course_key:'bipolar'}),row=Array.isArray(cur.data)?cur.data[0]:cur.data;if(!row)return;const loc=row.content?.[lang]||row.content?.fr||{};q('#competitionFormat').textContent=loc.title||(lang==='en'?'The forgotten episode':'L’épisode oublié');const lb=await c.rpc('get_challenge_leaderboard',{p_challenge_key:row.challenge_key,p_limit:100}),rows=lb.data||[],top=rows[0],mine=rows.find(x=>x.user_id===user.id),ids=rows.slice(0,7).map(x=>x.user_id);let pmap=new Map();if(ids.length){try{const {data:pub}=await c.rpc('get_public_profiles',{p_user_ids:ids});(pub||[]).forEach(x=>pmap.set(x.id,x))}catch(_){}}
q('#competitionParticipants').textContent=String(rows.length);q('#competitionMyRank').textContent=mine?'#'+mine.rank:'—';if(top){const pp=pmap.get(top.user_id)||{};q('#competitionHolderName').textContent=top.display_name;q('#competitionHolderMeta').textContent=[compact(pp.professional_status||pp.residency_year,lang),`${Number(top.score||0).toFixed(1)} / 100`].filter(Boolean).join(' · ')}
if(mine&&top&&mine.user_id!==top.user_id)q('#competitionGap').textContent=(Number(top.score||0)-Number(mine.score||0)).toFixed(1)+(lang==='en'?' points separate you from the current leader.':' points vous séparent du titulaire actuel.');else if(mine&&top&&mine.user_id===top.user_id)q('#competitionGap').textContent=lang==='en'?'You currently hold the coat.':'Vous détenez actuellement la blouse.';else q('#competitionGap').textContent=lang==='en'?'Complete the weekly case to enter the ranking.':'Terminez le dossier de la semaine pour entrer au classement.';
const end=new Date(row.ends_at);if(!Number.isNaN(end.getTime())){const rem=Math.max(0,end-Date.now()),d=Math.floor(rem/86400000),h=Math.floor((rem%86400000)/3600000),m=Math.floor((rem%3600000)/60000);q('#competitionCountdown').textContent=`◷ ${d} j ${h} h ${m} min`}
q('#competitionLeaderboard').innerHTML=rows.slice(0,5).map(r=>{const pp=pmap.get(r.user_id)||{},st=compact(pp.professional_status||pp.residency_year,lang);return `<div class="ps61-rank"><span class="num">${r.rank}</span><div><b>${r.display_name}${r.user_id===user.id?' · '+(lang==='en'?'You':'Vous'):''}</b><small>${st}</small></div><strong>${Number(r.score||0).toFixed(1)}</strong></div>`}).join('')||'<span style="color:var(--61-muted)">—</span>'}catch(_){q('#competitionLeaderboard').innerHTML='<span style="color:var(--61-muted)">—</span>'}});
})();
