(function(){
const q=s=>document.querySelector(s),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),preview=new URLSearchParams(location.search).get('preview')==='1';
const art={psychosis:'assets/v71/psychose.jpg',anxiety:'assets/v71/anxiete.jpg',addiction:'assets/v71/addicto.jpg'};
const names={fr:{psychosis:['PsychoseLab','Spectre de la psychose'],anxiety:['AnxiétéLab','Troubles anxieux'],addiction:['AddictoLab','Troubles addictifs']},en:{psychosis:['PsychosisLab','Psychosis spectrum'],anxiety:['AnxietyLab','Anxiety disorders'],addiction:['AddictionLab','Addictive disorders']}};
const desc={fr:{psychosis:'Explorer la sémiologie des expériences psychotiques et leur lecture clinique.',anxiety:'Approfondir les troubles anxieux et leurs principaux repères cliniques.',addiction:'Comprendre les troubles addictifs, leurs comorbidités et leur évaluation.'},en:{psychosis:'Explore the psychopathology of psychotic experiences and their clinical reading.',anxiety:'Deepen your understanding of anxiety disorders and key clinical markers.',addiction:'Understand addictive disorders, comorbidities and clinical assessment.'}};
function pct(ctx,key='bipolar'){if(preview&&key==='bipolar')return 46;const p=(ctx?.progress||[]).find(x=>x.course_key===key),raw=Number(p?.course_score||0);return raw?Math.min(100,Math.round(raw>100?raw/10:raw)):0}
async function progress(ctx){if(preview||!ctx?.client||!ctx?.user)return ctx?.progress||[];try{const {data}=await ctx.client.from('course_progress').select('course_key,course_score').eq('user_id',ctx.user.id);return data||[]}catch(_){return[]}}
function render(ctx){const lang=window.PsyLabV60?.lang?.()||'fr',p=pct(ctx);if(q('#labsProgressStat'))q('#labsProgressStat').textContent=p+'%';if(q('#featuredLab'))q('#featuredLab').innerHTML=`<article class="ps-featured-lab"><div class="ps-featured-copy"><small>${lang==='en'?'LAB 01 · ACTIVE':'LAB 01 · ACTIF'}</small><h2>BipolarLab</h2><h3>${lang==='en'?'Bipolar disorders':'Troubles bipolaires'}</h3><p>${lang==='en'?'A structured path to master psychopathology, longitudinal diagnosis and clinical management.':'Un parcours structuré pour maîtriser la sémiologie, le diagnostic longitudinal et la prise en charge.'}</p><div class="ps-featured-meta"><div class="ps-progress"><i style="width:${p}%"></i></div><strong>${p}%</strong></div><a class="ps-btn paper" href="courses/bipolar/index.html">${lang==='en'?'Access the Lab':'Accéder au Lab'} →</a></div></article>`;const box=q('#catalog');if(!box)return;box.innerHTML=['psychosis','anxiety','addiction'].map((key,i)=>{const n=names[lang]?.[key]||names.fr[key],d=desc[lang]?.[key]||desc.fr[key];return `<article class="ps-course-card"><div class="ps-course-art"><img src="${art[key]}" alt=""></div><div class="ps-course-body"><div class="ps-course-index"><span>LAB 0${i+2}</span><span>${lang==='en'?'COMING SOON':'À VENIR'}</span></div><h2>${esc(n[0])}</h2><p class="sub">${esc(n[1])}</p><p>${esc(d)}</p><span class="ps-course-status">${lang==='en'?'Coming soon':'À venir'}</span></div></article>`}).join('')}
window.addEventListener('psylab:v60-page-ready',async e=>{const p=await progress(e.detail);render({...e.detail,progress:p})});if(preview&&document.readyState!=='loading')render({progress:[{course_key:'bipolar',course_score:46}]});
})();
