(function(){
const q=s=>document.querySelector(s),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const preview=new URLSearchParams(location.search).get('preview')==='1';
const art={bipolar:'assets/v70/bipolar.jpg',psychosis:'assets/v70/psychose.jpg',anxiety:'assets/v70/anxiete.jpg',addiction:'assets/v70/addicto.jpg'};
const names={fr:{bipolar:['BipolarLab','Troubles bipolaires'],psychosis:['PsychoseLab','Spectre de la psychose'],anxiety:['AnxiétéLab','Troubles anxieux'],addiction:['AddictoLab','Troubles addictifs']},en:{bipolar:['BipolarLab','Bipolar disorders'],psychosis:['PsychosisLab','Psychosis spectrum'],anxiety:['AnxietyLab','Anxiety disorders'],addiction:['AddictionLab','Addictive disorders']}};
const desc={fr:{psychosis:'Explorer la sémiologie des expériences psychotiques et leur lecture clinique.',anxiety:'Approfondir les troubles anxieux et leurs principaux repères cliniques.',addiction:'Comprendre les troubles addictifs, leurs comorbidités et leur évaluation.'},en:{psychosis:'Explore the psychopathology of psychotic experiences and their clinical reading.',anxiety:'Deepen your understanding of anxiety disorders and key clinical markers.',addiction:'Understand addictive disorders, comorbidities and clinical assessment.'}};
function pct(ctx,key){if(preview&&key==='bipolar')return 46;const p=(ctx?.progress||[]).find(x=>x.course_key===key),raw=Number(p?.course_score||0);return raw?Math.min(100,Math.round(raw>100?raw/10:raw)):0}
async function loadProgress(ctx){if(preview||!ctx?.client||!ctx?.user)return ctx?.progress||[];try{const {data}=await ctx.client.from('course_progress').select('course_key,course_score').eq('user_id',ctx.user.id);return data||[]}catch(_){return ctx?.progress||[]}}
function render(ctx){const lang=window.PsyLabV60?.lang?.()||'fr',courses=window.PSYLAB_COURSES||[],p=pct(ctx,'bipolar'),active=courses.find(c=>c.key==='bipolar')||courses.find(c=>c.status==='active');
 const featured=q('#featuredLab');if(featured){const href=active?window.PsyLabV60.courseHref(active):'courses/bipolar/index.html';featured.innerHTML=`<article class="v70-featured-lab"><div class="v70-featured-copy"><small>${lang==='en'?'LAB 01 · ACTIVE':'LAB 01 · ACTIF'}</small><h2>BipolarLab</h2><h3>${lang==='en'?'Bipolar disorders':'Troubles bipolaires'}</h3><p>${lang==='en'?'A structured path to master psychopathology, longitudinal diagnosis and clinical management.':'Un parcours structuré pour maîtriser la sémiologie, le diagnostic longitudinal et la prise en charge.'}</p><div class="v70-featured-meta"><div class="v70-progress"><i style="width:${p}%"></i></div><strong>${p}%</strong></div><a class="v70-btn" href="${href}">${lang==='en'?'Access the Lab':'Accéder au Lab'} <span class="v70-arrow">→</span></a></div></article>`}
 const box=q('#catalog');if(!box)return;const keys=['psychosis','anxiety','addiction'];box.innerHTML=keys.map((key,i)=>{const n=names[lang]?.[key]||names.fr[key],d=desc[lang]?.[key]||desc.fr[key];return `<article class="v70-course-card"><div class="v70-course-art"><img src="${art[key]}" alt=""></div><div class="v70-course-body"><div class="v70-course-index"><span>LAB 0${i+2}</span><span>${lang==='en'?'COMING SOON':'À VENIR'}</span></div><h2>${esc(n[0])}</h2><p class="sub">${esc(n[1])}</p><p>${esc(d)}</p><span class="v70-course-status">${lang==='en'?'Coming soon':'À venir'}</span></div></article>`}).join('')}
window.addEventListener('psylab:v60-page-ready',async e=>{const progress=await loadProgress(e.detail);render({...e.detail,progress})});
if(preview&&document.readyState!=='loading')render({progress:[{course_key:'bipolar',course_score:46}]});
})();
