(function(){
const q=s=>document.querySelector(s);const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function initials(n){return String(n||'R').trim().split(/\s+/).slice(0,2).map(x=>x[0]).join('').toUpperCase()||'R'}
function compactStatus(v,lang){v=String(v||'').toUpperCase();if(/^R[1-4]$/.test(v))return v;const fr={EXTERNE:'Externe',INTERNE:'Interne',ASSISTANT:'Assistant',PROFESSEUR:'Professeur'},en={EXTERNE:'Extern',INTERNE:'Intern',ASSISTANT:'Assistant',PROFESSEUR:'Professor'};return (lang==='en'?en:fr)[v]||v}
function teaserTitle(loc,lang){const t=String(loc?.display_title||loc?.short_title||'').trim();if(t&&t.length<=52&&!/(diagnostic|syndrome|mania|manie|bipol|cortic|médicament|medication)/i.test(t))return t;return lang==='en'?'The False Obvious':'Le Faux Évident'}
function localMetrics(){try{const s=JSON.parse(localStorage.getItem('bplabV40')||'{}'),n=JSON.parse(localStorage.getItem('bplabN2V44')||'{}');const vals=o=>Object.values(o||{}),dis=vals(s.levels).filter(v=>Number(v)>=2).length,mem=vals(s.memory).filter(v=>v==='solid').length,duels=vals(s.duels).filter(Boolean).length,st=vals(n.stations).filter(v=>v==='acquis').length;return Math.max(0,Math.min(100,Math.round((dis/50*.35+mem/50*.25+Math.min(duels,30)/30*.15+Math.min(st,30)/30*.25)*100)))}catch(_){return 0}}
function pct(ctx,key='bipolar'){const p=(ctx.progress||[]).find(x=>x.course_key===key),raw=Number(p?.course_score||0);return raw?Math.min(100,Math.round(raw>100?raw/10:raw)):key==='bipolar'?localMetrics():0}
async function signedAvatar(c,path){if(!path)return'';try{const {data,error}=await c.storage.from('avatars').createSignedUrl(path,3600);return error?'':(data?.signedUrl||'')}catch(_){return''}}
function quote(lang){const bank={fr:[['« La médecine est une science de l’incertitude et un art de la probabilité. »','William Osler']],en:[['“Medicine is a science of uncertainty and an art of probability.”','William Osler']]};return bank[lang][0]}
function renderIdentity(ctx){const lang=window.PsyLabV60.lang(),name=ctx.profile?.display_name||ctx.user.user_metadata?.display_name||ctx.user.user_metadata?.full_name||ctx.user.email?.split('@')[0]||(lang==='en'?'User':'Utilisateur'),status=compactStatus(ctx.profile?.professional_status||ctx.profile?.residency_year,lang),hour=new Date().getHours(),hello=lang==='en'?(hour>=18?'Good evening':'Hello'):(hour>=18?'Bonsoir':'Bonjour'),p=pct(ctx);q('#greeting').innerHTML=`${hello}, <span>${esc(name)}</span>.`;q('#userMeta').textContent=[status,`BipolarLab ${p}%`].filter(Boolean).join(' · ');q('#userName').textContent=name;q('#userSub').textContent=status;q('#topAvatar').textContent=initials(name);q('#resumePct').textContent=p+'%';q('#resumeBar').style.width=p+'%';signedAvatar(ctx.client,ctx.profile?.avatar_path).then(u=>{if(u)q('#topAvatar').innerHTML=`<img src="${u}" alt="">`});const [text,author]=quote(lang);q('#quoteText').textContent=text;q('#quoteAuthor').textContent='— '+author}
function renderLabs(ctx){const lang=window.PsyLabV60.lang(),catalog=(window.PSYLAB_COURSES||[]).slice(0,4),box=q('#labsGrid');box.innerHTML=catalog.map((c,i)=>{const active=c.status==='active',p=active?pct(ctx,c.key):0,href=active?window.PsyLabV60.courseHref(c):'labs.html',title=lang==='en'?c.title_en:c.title_fr,sub=lang==='en'?c.subtitle_en:c.subtitle_fr;return `<a class="ps66-lab-mini ${active?'active':'planned'}" href="${href}"><div class="ps66-lab-num">0${i+1}</div><div><small>${active?(lang==='en'?'IN PROGRESS':'EN COURS'):(lang==='en'?'COMING SOON':'À VENIR')}</small><h3>${esc(title)}</h3><p>${esc(sub)}</p>${active?`<div class="ps66-mini-progress"><i style="width:${p}%"></i></div>`:''}</div><span>${active?(lang==='en'?'Continue':'Continuer'):'→'}</span></a>`}).join('')}
function renderMaintenance(ctx){const lang=window.PsyLabV60.lang(),unlocked=pct(ctx)>=100,card=q('#maintenanceCard'),copy=q('#maintenanceCopy'),arr=q('#maintenanceArrow');if(unlocked){copy.textContent=lang==='en'?'A spaced-review session is ready.':'Une session de révision espacée est disponible.';arr.textContent='→';card.classList.add('ready');card.onclick=()=>location.href='maintenance.html'}else{arr.textContent=lang==='en'?'After your first Lab':'Après votre premier Lab';card.classList.remove('ready');card.onclick=null}}
async function renderBlouse(ctx){const c=ctx.client,lang=window.PsyLabV60.lang();try{const current=await c.rpc('get_current_challenge',{p_course_key:'bipolar'}),row=Array.isArray(current.data)?current.data[0]:current.data;if(!row)return;const loc=row.content?.[lang]||row.content?.fr||{};q('#weekCase').textContent=teaserTitle(loc,lang);const lb=await c.rpc('get_challenge_leaderboard',{p_challenge_key:row.challenge_key,p_limit:100}),rows=lb.data||[],top=rows[0];q('#participantCount').textContent=String(rows.length);if(top){q('#holderName').textContent=top.display_name;let pub=null;try{const r=await c.rpc('get_public_profiles',{p_user_ids:[top.user_id]});pub=r.data?.[0]}catch(_){}const st=compactStatus(pub?.professional_status||pub?.residency_year,lang);q('#holderMeta').textContent=st}else{q('#holderName').textContent=lang==='en'?'To be claimed':'À prendre';q('#holderMeta').textContent=''}const end=new Date(row.ends_at);if(!Number.isNaN(end.getTime())){const rem=Math.max(0,end-Date.now()),d=Math.floor(rem/86400000),h=Math.floor((rem%86400000)/3600000);q('#countdown').textContent=`${d}j ${h}h`}}
catch(_){} }
window.addEventListener('psylab:v60-ready',e=>{const ctx=e.detail;renderIdentity(ctx);renderLabs(ctx);renderMaintenance(ctx);renderBlouse(ctx)});
})();
