(function(){
'use strict';
const en=(document.documentElement.lang||'').startsWith('en');
const T=en?{activity:'Your learning activity',activityP:'Frequency, active time and current weak points are calculated from real learning interactions — not simply from time spent with a tab open.',days:'Active days / 7',mins:'Active minutes / 30 days',events:'Learning events / 30 days',accuracy:'Accuracy / 30 days',weak:'Current weak points',weakEmpty:'No stable weak point has been detected yet.',chair:'The Staff Chair',chairP:'A weekly clinical case shared by residents. One ranked attempt; speed does not add points.',open:'Open the challenge',summary:'Progress & trophies',trophies:'Trophies',score:'PsyScore',close:'Close'}:{activity:'Votre activité d’apprentissage',activityP:'Fréquence, temps actif et points faibles sont calculés à partir des interactions pédagogiques réelles — pas simplement du temps pendant lequel un onglet reste ouvert.',days:'Jours actifs / 7',mins:'Minutes actives / 30 j',events:'Événements pédagogiques / 30 j',accuracy:'Précision / 30 j',weak:'Points faibles actuels',weakEmpty:'Aucun point faible stable n’a encore été détecté.',chair:'Le Fauteuil du Staff',chairP:'Un dossier clinique hebdomadaire commun aux résidents. Une tentative classée ; la vitesse ne rapporte aucun point.',open:'Ouvrir le challenge',summary:'Progression & trophées',trophies:'Trophées',score:'PsyScore',close:'Fermer'};
const labels={
 'n1.sleep':en?'Sleep phenomenology':'Sommeil','n1.thought':en?'Thought form and course':'Cours et forme de la pensée','n1.speech':en?'Speech and language':'Discours et langage','n1.attention':en?'Attention':'Attention','n1.mood_affect':en?'Mood and affect':'Humeur et affect','n1.motivation':en?'Motivation, energy and volition':'Motivation, énergie et volition','n1.psychomotor':en?'Psychomotor activity':'Psychomotricité','n1.insight_judgment':en?'Insight and judgment':'Insight et jugement','n1.other':en?'Descriptive psychopathology':'Psychopathologie descriptive','n2.representation':en?'Problem representation':'Représentation du problème','n2.branching':en?'Diagnostic branching':'Ouverture de l’arbre diagnostique','n2.causality':en?'Causal reasoning':'Raisonnement causal','n2.closure':en?'Premature closure':'Fermeture prématurée','n2.differential':en?'Differential diagnosis':'Diagnostic différentiel','n2.evidence':en?'Evidence weighting':'Pondération des preuves','n2.information':en?'Information gathering':'Recherche d’information','n2.threshold':en?'Diagnostic thresholds':'Seuils diagnostiques','n2.uncertainty':en?'Uncertainty calibration':'Calibration de l’incertitude','n2.nosology':en?'Nosological architecture':'Architecture nosologique','n2.formulation':en?'Clinical formulation':'Formulation clinique','psychometrics.selection':en?'Scale selection':'Choix des échelles'
};
function label(k){return labels[k]||String(k||'').replace(/^n[12]\./,'').replaceAll('_',' ')}
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function local(){return window.PsyLabLearning?.localAggregate?.('bipolar')||{active_days_7:0,active_seconds_30:0,event_count_30:0,accuracy_30:null,weaknesses:[]}}
function injectActivity(){if(document.getElementById('v51Activity'))return;const labs=document.getElementById('labs');if(!labs)return;const s=document.createElement('section');s.className='wrap activity-section';s.id='v51Activity';s.innerHTML=`<div class="section-title-row"><div><div class="eyebrow dark">LEARNING ANALYTICS</div><h2>${T.activity}</h2></div><div class="catalog-note">${T.activityP}</div></div><div class="activity-grid"><article class="activity-card"><div class="activity-metrics"><div class="activity-metric"><b id="v51pDays">0</b><span>${T.days}</span></div><div class="activity-metric"><b id="v51pMins">0</b><span>${T.mins}</span></div><div class="activity-metric"><b id="v51pEvents">0</b><span>${T.events}</span></div><div class="activity-metric"><b id="v51pAccuracy">—</b><span>${T.accuracy}</span></div></div><h3>${T.weak}</h3><div class="weakness-list" id="v51pWeak"></div></article><article class="activity-card chair-card"><div class="eyebrow">WEEKLY CLINICAL CHALLENGE</div><h3>🪑 ${T.chair}</h3><p>${T.chairP}</p><a href="${en?'courses/bipolar/en.html#v51-challenge':'courses/bipolar/index.html#v51-challenge'}">${T.open} →</a></article></div>`;labs.parentNode.insertBefore(s,labs);renderLocal()}
function renderData(d){d=d||local();document.getElementById('v51pDays')&&(document.getElementById('v51pDays').textContent=d.active_days_7||0);document.getElementById('v51pMins')&&(document.getElementById('v51pMins').textContent=Math.round((d.active_seconds_30||0)/60));document.getElementById('v51pEvents')&&(document.getElementById('v51pEvents').textContent=d.event_count_30||0);document.getElementById('v51pAccuracy')&&(document.getElementById('v51pAccuracy').textContent=d.accuracy_30==null?'—':Math.round(d.accuracy_30)+'%');const w=document.getElementById('v51pWeak');if(w){const rows=d.weaknesses||[];w.innerHTML=rows.length?rows.slice(0,5).map(x=>`<div class="weakness-row"><b>${esc(label(x.key||x.competency_key))}</b><span>${Math.round(x.mastery??x.mastery_score??0)}%</span></div>`).join(''):`<div class="empty-state">${T.weakEmpty}</div>`}}
function renderLocal(){renderData(local())}
async function cloudDashboard(){try{const cfg=window.PSYLAB_CONFIG||{},key=cfg.anonKey||cfg.publishableKey;if(!window.supabase||!cfg.url||!key)return;window.__PSYLAB_V51_PLATFORM=window.__PSYLAB_V51_PLATFORM||window.supabase.createClient(cfg.url,key,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:false}});const c=window.__PSYLAB_V51_PLATFORM,{data:s}=await c.auth.getSession();if(!s?.session?.user)return;const {data,error}=await c.rpc('get_my_learning_dashboard',{p_course_key:'bipolar'});if(error)return;const row=Array.isArray(data)?data[0]:data;if(row){const d=row.dashboard||row;renderData(d)}}catch(e){}}
function installSummary(){if(document.getElementById('v51SummaryModal'))return;const m=document.createElement('div');m.className='modal-backdrop';m.id='v51SummaryModal';m.setAttribute('aria-hidden','true');m.innerHTML=`<section class="modal-card"><div class="modal-head"><div><div class="eyebrow dark">PSYLAB</div><h2>${T.summary}</h2></div><button class="icon-btn" data-v51-close>×</button></div><div class="summary-modal-grid"><div class="summary-modal-box"><b id="v51ModalTrophies">0</b><span>${T.trophies}</span></div><div class="summary-modal-box"><b id="v51ModalScore">0</b><span>${T.score}</span></div></div><div class="row-actions" style="margin-top:16px"><a class="primary-btn" href="${en?'courses/bipolar/en.html#badges':'courses/bipolar/index.html#badges'}">BipolarLab · ${T.trophies}</a></div></section>`;document.body.appendChild(m);m.querySelector('[data-v51-close]').onclick=()=>{m.classList.remove('show');m.setAttribute('aria-hidden','true')};m.onclick=e=>{if(e.target===m){m.classList.remove('show');m.setAttribute('aria-hidden','true')}}}
function openSummary(){installSummary();document.getElementById('v51ModalTrophies').textContent=document.getElementById('totalTrophies')?.textContent||'0';document.getElementById('v51ModalScore').textContent=document.getElementById('globalScore')?.textContent||'0';const m=document.getElementById('v51SummaryModal');m.classList.add('show');m.setAttribute('aria-hidden','false')}
function fixMobileNav(){const nav=document.querySelector('.mobile-app-nav');if(!nav)return;const items=[...nav.children];items.forEach(x=>{x.style.pointerEvents='auto';x.style.touchAction='manipulation'});const home=nav.querySelector('a[href="#appMain"]'),labs=nav.querySelector('a[href="#labs"]'),trophy=document.getElementById('mobileTrophies'),profile=document.getElementById('mobileProfile');if(home)home.addEventListener('click',e=>{e.preventDefault();document.getElementById('appMain')?.scrollIntoView({behavior:'smooth'});items.forEach(x=>x.classList.remove('active'));home.classList.add('active')});if(labs)labs.addEventListener('click',e=>{e.preventDefault();document.getElementById('labs')?.scrollIntoView({behavior:'smooth'});items.forEach(x=>x.classList.remove('active'));labs.classList.add('active')});if(trophy)trophy.addEventListener('click',e=>{e.preventDefault();openSummary();items.forEach(x=>x.classList.remove('active'));trophy.classList.add('active')});if(profile)profile.addEventListener('click',e=>{e.preventDefault();const m=document.getElementById('accountModal');if(m){m.classList.add('show');m.setAttribute('aria-hidden','false')}try{if(typeof showPane==='function')showPane('profile')}catch(_){ }items.forEach(x=>x.classList.remove('active'));profile.classList.add('active')})}
function init(){injectActivity();installSummary();fixMobileNav();renderLocal();setTimeout(cloudDashboard,1200);setInterval(cloudDashboard,30000);window.addEventListener('storage',e=>{if(e.key==='psylabLearningV51')renderLocal()})}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();
