(function(){
const q=s=>document.querySelector(s); const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function initials(n){return String(n||'R').trim().split(/\s+/).slice(0,2).map(x=>x[0]).join('').toUpperCase()||'R'}
function compactStatus(v,lang){v=String(v||'').toUpperCase();if(/^R[1-4]$/.test(v))return v;const fr={EXTERNE:'Externe',INTERNE:'Interne',ASSISTANT:'Assistant',PROFESSEUR:'Professeur'},en={EXTERNE:'Extern',INTERNE:'Intern',ASSISTANT:'Assistant',PROFESSEUR:'Professor'};return (lang==='en'?en:fr)[v]||v}
function localMetrics(){try{const s=JSON.parse(localStorage.getItem('bplabV40')||'{}'),n=JSON.parse(localStorage.getItem('bplabN2V44')||'{}');const vals=o=>Object.values(o||{}),dis=vals(s.levels).filter(v=>Number(v)>=2).length,mem=vals(s.memory).filter(v=>v==='solid').length,duels=vals(s.duels).filter(Boolean).length,st=vals(n.stations).filter(v=>v==='acquis').length;return Math.max(0,Math.min(100,Math.round((dis/50*.35+mem/50*.25+Math.min(duels,30)/30*.15+Math.min(st,30)/30*.25)*100)))}catch(_){return 0}}
function pct(ctx,key='bipolar'){const p=(ctx.progress||[]).find(x=>x.course_key===key),raw=Number(p?.course_score||0);return raw?Math.min(100,Math.round(raw>100?raw/10:raw)):key==='bipolar'?localMetrics():0}
async function signedAvatar(c,path){if(!path)return'';try{const {data,error}=await c.storage.from('avatars').createSignedUrl(path,3600);return error?'':(data?.signedUrl||'')}catch(_){return''}}
function quote(lang){const bank={fr:[['« Mieux comprendre l’autre, c’est déjà prendre soin. »','Philippe Pinel'],['« Le bon médecin traite la maladie ; le grand médecin traite le patient qui a la maladie. »','William Osler'],['« Lorsque nous ne pouvons plus changer une situation, nous sommes mis au défi de nous changer nous-mêmes. »','Viktor E. Frankl']],en:[['“The good physician treats the disease; the great physician treats the patient who has the disease.”','William Osler'],['“When we are no longer able to change a situation, we are challenged to change ourselves.”','Viktor E. Frankl'],['“The curious paradox is that when I accept myself just as I am, then I can change.”','Carl Rogers']]};return bank[lang][Math.floor(Date.now()/86400000)%bank[lang].length]}
function renderIdentity(ctx){const lang=window.PsyLabV60.lang(),name=ctx.profile?.display_name||ctx.user.user_metadata?.display_name||ctx.user.user_metadata?.full_name||ctx.user.email?.split('@')[0]||(lang==='en'?'User':'Utilisateur'),status=compactStatus(ctx.profile?.professional_status||ctx.profile?.residency_year,lang),hour=new Date().getHours(),hello=lang==='en'?(hour>=18?'Good evening':'Hello'):(hour>=18?'Bonsoir':'Bonjour'),p=pct(ctx);q('#greeting').innerHTML=`${hello}, <span>${esc(name)}</span> 👋`;q('#userMeta').textContent=[status,`BipolarLab ${p}%`].filter(Boolean).join(' · ');q('#userName').textContent=name;q('#userSub').textContent=status;q('#topAvatar').textContent=initials(name);signedAvatar(ctx.client,ctx.profile?.avatar_path).then(u=>{if(u)q('#topAvatar').innerHTML=`<img src="${u}" alt="">`});const [text,author]=quote(lang);q('#quoteText').textContent=text;q('#quoteAuthor').textContent='— '+author}
function renderLabs(ctx){const lang=window.PsyLabV60.lang(),catalog=(window.PSYLAB_COURSES||[]).slice(0,4),box=q('#labsGrid');box.innerHTML=catalog.map((c,i)=>{const active=c.status==='active',p=active?pct(ctx,c.key):0,href=active?window.PsyLabV60.courseHref(c):'labs.html',title=lang==='en'?c.title_en:c.title_fr,sub=lang==='en'?c.subtitle_en:c.subtitle_fr,level=lang==='en'?'Level 1 · Observe':'Niveau 1 · Observer',mission=lang==='en'?'Mission 4 · Thought process':'Mission 4 · Cours de la pensée';return `<a class="ps61-lab ${active?'active':'locked'}" href="${href}"><div class="ps61-lab-art"></div><div><h3>${esc(title)}</h3><p>${esc(sub)}</p>${active?`<div class="ps61-lab-progress"><i style="width:${p}%"></i></div><div class="ps61-lab-meta">${p}%</div><div class="ps61-lab-meta">⌂ ${level}</div><div class="ps61-lab-meta">◉ ${mission}</div>`:''}</div><span class="ps61-lab-cta">${active?(lang==='en'?'Continue →':'Continuer →'):(lang==='en'?'Coming soon':'Bientôt disponible')}</span></a>`}).join('')}
function renderMaintenance(ctx){const lang=window.PsyLabV60.lang(),unlocked=pct(ctx)>=100,card=q('#maintenanceCard'),copy=q('#maintenanceCopy'),arr=q('#maintenanceArrow');if(unlocked){copy.textContent=lang==='en'?'Your first spaced-review session is available.':'Votre première session de révision espacée est disponible.';arr.textContent='→';card.style.cursor='pointer';card.onclick=()=>location.href='maintenance.html'}else{arr.textContent='🔒';card.style.cursor='default';card.onclick=null}}
async function renderBlouse(ctx){const c=ctx.client,lang=window.PsyLabV60.lang();try{const current=await c.rpc('get_current_challenge',{p_course_key:'bipolar'}),row=Array.isArray(current.data)?current.data[0]:current.data;if(!row)return;const loc=row.content?.[lang]||row.content?.fr||{};q('#weekCase').textContent=loc.title||(lang==='en'?'The forgotten episode':'L’épisode oublié');const lb=await c.rpc('get_challenge_leaderboard',{p_challenge_key:row.challenge_key,p_limit:100}),rows=lb.data||[],top=rows[0];q('#participantCount').textContent=`${rows.length} ${window.PsyLabV60.tr('participants')}`;if(top){q('#holderName').textContent=top.display_name;let pub=null;try{const r=await c.rpc('get_public_profiles',{p_user_ids:[top.user_id]});pub=r.data?.[0]}catch(_){}const st=compactStatus(pub?.professional_status||pub?.residency_year,lang);q('#holderMeta').textContent=st;}
const end=new Date(row.ends_at);if(!Number.isNaN(end.getTime())){const rem=Math.max(0,end-Date.now()),d=Math.floor(rem/86400000),h=Math.floor((rem%86400000)/3600000);q('#countdown').textContent=`◷ ${d} j ${h} h`}}
catch(_){}}
window.addEventListener('psylab:v60-ready',e=>{const ctx=e.detail;renderIdentity(ctx);renderLabs(ctx);renderMaintenance(ctx);renderBlouse(ctx)});
})();
