(function(){
const q=s=>document.querySelector(s),qa=s=>[...document.querySelectorAll(s)];
const esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
function initials(n){return String(n||'R').trim().split(/\s+/).slice(0,2).map(x=>x[0]).join('').toUpperCase()||'R'}
function localMetrics(){try{const s=JSON.parse(localStorage.getItem('bplabV40')||'{}'),n=JSON.parse(localStorage.getItem('bplabN2V44')||'{}');const vals=o=>Object.values(o||{}),dis=vals(s.levels).filter(v=>Number(v)>=2).length,mem=vals(s.memory).filter(v=>v==='solid').length,duels=vals(s.duels).filter(Boolean).length,st=vals(n.stations).filter(v=>v==='acquis').length;const pct=Math.max(0,Math.min(100,Math.round((dis/50*.35+mem/50*.25+Math.min(duels,30)/30*.15+Math.min(st,30)/30*.25)*100)));return pct}catch(_){return 0}}
function localLearning(){try{return window.PsyLabLearning?.localAggregate?.('bipolar')||{active_days_7:0,weaknesses:[]}}catch(_){return{active_days_7:0,weaknesses:[]}}}
function labelSkill(k){return({'temporalite.trait_vs_etat':'Temporalité · trait vs état','temporalite.episodicite':'Épisodicité','cours_pensee.vitesse_vs_direction':'Cours de pensée','raisonnement.fermeture_prematuree':'Fermeture prématurée','raisonnement.compatible_vs_discriminant':'Compatible vs discriminant','differentiel.hierarchisation':'Hiérarchisation différentielle','diagnostic.seuil_manie_hypomanie':'Seuil manie / hypomanie','incertitude.surconfiance':'Calibration de confiance','anamnese.information_collaterale':'Information collatérale'})[k]||String(k||'Compétence').replaceAll('_',' ')}
async function signedAvatar(c,path){if(!path)return'';try{const {data,error}=await c.storage.from('avatars').createSignedUrl(path,3600);return error?'':data?.signedUrl||''}catch(_){return''}}
async function publicAvatarMap(c,ids){const map=new Map();if(!ids.length)return map;try{const {data,error}=await c.rpc('get_public_profiles',{p_user_ids:ids});if(error)return map;await Promise.all((data||[]).map(async p=>{if(!p.avatar_path)return;const u=await signedAvatar(c,p.avatar_path);if(u)map.set(p.id,u)}));return map}catch(_){return map}}
function setUser(ctx){const name=ctx.profile?.display_name||ctx.user.user_metadata?.display_name||'Résident',sub=[ctx.profile?.residency_year,ctx.profile?.cohort_code].filter(Boolean).join(' · ')||'Résident';q('#homeUserName').textContent=name;q('#homeUserSub').textContent=sub;const a=q('#homeAvatar');a.textContent=initials(name);signedAvatar(ctx.client,ctx.profile?.avatar_path).then(u=>{if(u)a.innerHTML='<img src="'+u+'" alt="Photo de profil">'});q('#resumeHello').textContent='Continuer là où vous en étiez';}
function renderLabs(ctx){const box=q('#homeLabs'),catalog=window.PSYLAB_COURSES||[],prog=new Map((ctx.progress||[]).map(x=>[x.course_key,x]));box.innerHTML=catalog.slice(0,3).map(c=>{const active=c.status==='active',score=active?Math.round(Number((prog.get(c.key)||{}).course_score||0)/10):0,pct=active?(score||localMetrics()):0;return `<a class="v57-lab ${active?'active':''}" href="${active?c.href:'labs.html'}"><div class="v57-lab-icon">${esc(c.icon||'◌')}</div><h3>${esc(c.title_fr)}</h3><p>${esc(c.subtitle_fr)}</p><footer><span>${active?pct+'%':'Bientôt'}</span><span>→</span></footer></a>`}).join('')}
function renderLearning(){const d=localLearning(),weak=(d.weaknesses||[])[0];q('#activeDays').textContent=d.active_days_7||0;if(weak){q('#reviewTitle').textContent=labelSkill(weak.key||weak.competency_key);q('#reviewMeta').textContent=`${Math.round(Number(weak.mastery??weak.mastery_score??0))}% de maîtrise · révision courte recommandée`;q('#axoneHomeText').textContent=`Votre priorité actuelle : ${labelSkill(weak.key||weak.competency_key)}. Je vous conseille une courte révision, puis un nouveau cas sans indice.`}else{q('#reviewTitle').textContent='Consolider vos acquis';q('#reviewMeta').textContent='Une session courte sera proposée après vos prochaines activités.';q('#axoneHomeText').textContent='Je reste discret tant qu’aucun profil d’erreur stable ne mérite une révision ciblée.'}}
async function renderBlouse(ctx){const c=ctx.client;try{const current=await c.rpc('get_current_challenge',{p_course_key:'bipolar'});const row=Array.isArray(current.data)?current.data[0]:current.data;if(!row)return;const loc=row.content?.fr||{};q('#blouseWeekTitle').textContent=loc.title||'Le cas de la semaine';const [lb,se]=await Promise.all([c.rpc('get_challenge_leaderboard',{p_challenge_key:row.challenge_key,p_limit:100}),c.rpc('get_season_leaderboard',{p_course_key:'bipolar',p_limit:100})]);const rows=lb.data||[],top=rows[0],mine=rows.find(x=>x.user_id===ctx.user.id);if(top){q('#blouseHolderName').textContent=top.display_name;q('#blouseHolderMeta').textContent=`${Number(top.score||0).toFixed(1)} / 100 · titulaire actuel`;const amap=await publicAvatarMap(c,[top.user_id]);const av=q('#blouseHolderAvatar');av.textContent=initials(top.display_name);const u=amap.get(top.user_id);if(u)av.innerHTML='<img src="'+u+'" alt="">'}else{q('#blouseHolderName').textContent='À prendre';q('#blouseHolderMeta').textContent='Aucune tentative classée pour le moment.'}if(mine)q('#homeBlouseStatus').textContent=`Vous êtes #${mine.rank}`;const end=new Date(row.ends_at);if(!Number.isNaN(end.getTime())){const rem=Math.max(0,end-Date.now()),d=Math.floor(rem/86400000),h=Math.floor((rem%86400000)/3600000);q('#blouseCountdown').textContent=`${d} j ${h} h restantes`}}
catch(_){}}
function renderActivity(){const box=q('#homeActivity');let rows=[];try{const d=window.PsyLabLearning?.localAggregate?.('bipolar');if(d?.event_count_30)rows.push(['✓','Activités enregistrées',`${d.event_count_30} interactions pédagogiques sur 30 jours`,'récent'])}catch(_){}rows.push(['◉','BipolarLab','Reprendre le parcours clinique','maintenant']);rows.push(['◎','Révision ciblée','Travaillez votre faiblesse actuelle','~ 7 min']);box.innerHTML=rows.slice(0,3).map(r=>`<div class="v57-activity-row"><i>${r[0]}</i><div><b>${esc(r[1])}</b><small>${esc(r[2])}</small></div><time>${esc(r[3])}</time></div>`).join('')}
function installSearch(){const input=q('#homeSearch');if(!input)return;input.addEventListener('keydown',e=>{if(e.key==='Enter'){const v=input.value.trim().toLowerCase();if(!v)return;if(/qcm|question|entrain/.test(v))location.href='training.html';else if(/cas|dossier/.test(v))location.href='cases.html';else if(/blouse|compétition|competition/.test(v))location.href='competition.html';else if(/bipol|manie|hypoman/.test(v))location.href='courses/bipolar/index.html';else location.href='labs.html'}});document.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'){e.preventDefault();input.focus()}})}
async function askAxone(ctx){const input=q('#homeAxoneQ'),state=q('#homeAxoneState'),text=input.value.trim();if(!text)return;const ep=window.PSYLAB_CONFIG?.aiEndpoint;if(!ep){state.textContent='Question libre non configurée. Les conseils contextuels restent disponibles gratuitement.';return}state.textContent='Dr Axone réfléchit…';try{const r=await fetch(ep,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({question:text,context:{surface:'PsyLab',course:'bipolar'}})}),d=await r.json();state.textContent=d.answer||d.response||'Réponse indisponible.'}catch(_){state.textContent='Module de question libre indisponible.'}}
window.addEventListener('psylab:v57-ready',async e=>{const ctx=e.detail;setUser(ctx);renderLabs(ctx);renderLearning();renderActivity();renderBlouse(ctx);q('#resumePct').textContent=localMetrics()+'%';q('#resumeBar').style.width=localMetrics()+'%';q('#homeAxoneAsk').onclick=()=>askAxone(ctx);q('#homeLogout').onclick=()=>window.PsyLabAuthV57.logout();});
installSearch();
})();
