(function(){
'use strict';
const en=(document.documentElement.lang||'').startsWith('en');
const T=en?{
 activity:'Learning activity',days:'Active days · 7 d',mins:'Active minutes · 30 d',events:'Activities · 30 d',accuracy:'First-pass accuracy',weak:'Current focus',weakEmpty:'No recurring weak point detected yet.',competition:'Everybody Wants the White Coat',competitionP:'The weekly clinical challenge.',open:'I want the coat',holder:'White Coat holder',noHolder:'Up for grabs',challengers:'residents in the race',summary:'Progress',trophies:'Trophies',score:'PsyScore'
}:{
 activity:'Activité',days:'Jours actifs · 7 j',mins:'Minutes actives · 30 j',events:'Activités · 30 j',accuracy:'Précision au 1er essai',weak:'Focus du moment',weakEmpty:'Aucun point faible récurrent détecté pour le moment.',competition:'Tout le monde veut la blouse',competitionP:'Le défi clinique hebdomadaire.',open:'Je veux la blouse',holder:'Titulaire de la Blouse',noHolder:'À prendre',challengers:'résidents dans la course',summary:'Progression',trophies:'Trophées',score:'PsyScore'
};
const labels={'n1.sleep':en?'Sleep':'Sommeil','n1.thought':en?'Thought form and course':'Cours et forme de la pensée','n1.speech':en?'Speech and language':'Discours et langage','n1.attention':en?'Attention':'Attention','n1.mood_affect':en?'Mood and affect':'Humeur et affect','n1.motivation':en?'Motivation and volition':'Motivation et volition','n1.psychomotor':en?'Psychomotor activity':'Psychomotricité','n1.insight_judgment':en?'Insight and judgment':'Insight et jugement','n1.other':en?'Descriptive psychopathology':'Psychopathologie descriptive','n2.representation':en?'Problem representation':'Représentation du problème','n2.branching':en?'Diagnostic branching':'Ouverture des hypothèses','n2.causality':en?'Temporality / causality':'Temporalité / causalité','n2.closure':en?'Premature closure':'Fermeture prématurée','n2.differential':en?'Differential diagnosis':'Diagnostic différentiel','n2.evidence':en?'Evidence weighting':'Pondération des preuves','n2.information':en?'Information value':'Valeur de l’information','n2.threshold':en?'Diagnostic thresholds':'Seuils diagnostiques','n2.uncertainty':en?'Uncertainty calibration':'Calibration de l’incertitude','n2.nosology':en?'Nosology':'Nosographie','n2.formulation':en?'Clinical formulation':'Formulation clinique','psychometrics.selection':en?'Scale selection':'Choix des échelles'};
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function label(k){return labels[k]||String(k||'').replace(/^n[12]\./,'').replaceAll('_',' ')}
function local(){return window.PsyLabLearning?.localAggregate?.('bipolar')||{active_days_7:0,active_seconds_30:0,event_count_30:0,accuracy_30:null,weaknesses:[]}}
function coatSvg(){return `<svg viewBox="0 0 190 220" aria-hidden="true"><path class="coat-body" d="M66 20 92 38h6l26-18 26 18-11 50 17 112H34L51 88 40 38Z"/><path class="coat-line" d="M66 20 80 63 95 43 110 63 124 20M95 43v151M52 91l-23 76M138 91l23 76M52 129h27v27H47M111 129h27l5 27h-32"/><path class="coat-line" d="M73 20c3 15 10 22 22 23M117 20c-3 15-10 22-22 23"/></svg>`}
function updateResume(){try{const s=JSON.parse(localStorage.getItem('bplabV40')||'{}'),n=JSON.parse(localStorage.getItem('bplabN2V44')||'{}');const has=Object.keys(s||{}).length||Object.keys(n||{}).length;const courseCard=[...document.querySelectorAll('.course-card')].find(x=>x.querySelector('h3')?.textContent.trim()==='BipolarLab');const lbl=courseCard?.querySelector('.course-progress-label')?.textContent||'';const m=lbl.match(/·\s*(\d+)%/);const pct=m?Number(m[1]):(has?1:0);const el=document.getElementById('resumeScore');if(el)el.textContent=pct+'%';const a=document.getElementById('resumeBipolar');if(a)a.href=en?'courses/bipolar/en.html':'courses/bipolar/index.html'}catch(e){}}
function injectActivity(){if(document.getElementById('v52Activity'))return;const labs=document.getElementById('labs');if(!labs)return;const s=document.createElement('section');s.className='wrap v52-activity-section';s.id='v52Activity';s.innerHTML=`<div class="v52-activity-head"><div><div class="eyebrow dark">${en?'LEARNING':'SUIVI'}</div><h2>${T.activity}</h2></div></div><div class="v52-activity-grid"><article class="v52-activity-card"><div class="v52-metrics"><div class="v52-metric"><b id="v52Days">0</b><span>${T.days}</span></div><div class="v52-metric"><b id="v52Mins">0</b><span>${T.mins}</span></div><div class="v52-metric"><b id="v52Events">0</b><span>${T.events}</span></div><div class="v52-metric"><b id="v52Accuracy">—</b><span>${T.accuracy}</span></div></div><div class="v52-focus"><h3>${T.weak}</h3><div class="weakness-list" id="v52Weak"></div></div></article><article class="v52-activity-card v53-coat-card"><div class="v53-competition-copy"><div class="challenge-label">${en?'CLINICAL COMPETITION':'COMPÉTITION CLINIQUE'}</div><h3>${T.competition}</h3><p id="v53ChallengeTitle">${T.competitionP}</p><div class="v53-holder"><span>${T.holder}</span><b id="v53Holder">${T.noHolder}</b></div><div class="v53-chase"><b id="v53ChallengerCount">—</b><span>${T.challengers}</span></div><a class="v53-coat-action" href="${en?'courses/bipolar/en.html?open=blouse#v52-challenge':'courses/bipolar/index.html?open=blouse#v52-challenge'}">${T.open}</a></div><div class="v53-coat-trophy"><div class="v53-coat-art">${coatSvg()}<div class="v53-coat-badge"><small>PSYLAB</small><b id="v53CoatName">${T.noHolder}</b></div></div></div></article></div>`;labs.parentNode.insertBefore(s,labs);render(local())}
function render(d){d=d||local();const set=(id,v)=>{const el=document.getElementById(id);if(el)el.textContent=v};set('v52Days',d.active_days_7||0);set('v52Mins',Math.round((d.active_seconds_30||0)/60));set('v52Events',d.event_count_30||0);set('v52Accuracy',d.accuracy_30==null?'—':Math.round(d.accuracy_30)+'%');const w=document.getElementById('v52Weak');if(w){const rows=d.weaknesses||[];w.innerHTML=rows.length?rows.slice(0,4).map(x=>`<div class="weakness-row"><b>${esc(label(x.key||x.competency_key))}</b><span>${Math.round(x.mastery??x.mastery_score??0)}%</span></div>`).join(''):`<div class="empty-state">${T.weakEmpty}</div>`}updateResume()}
function getPlatformClient(){try{const cfg=window.PSYLAB_CONFIG||{},key=cfg.anonKey||cfg.publishableKey;if(!window.supabase||!cfg.url||!key)return null;window.__PSYLAB_V53_PLATFORM=window.__PSYLAB_V53_PLATFORM||window.supabase.createClient(cfg.url,key,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:false}});return window.__PSYLAB_V53_PLATFORM}catch(e){return null}}
async function cloudDashboard(){try{const c=getPlatformClient();if(!c)return;const {data:s}=await c.auth.getSession();if(!s?.session?.user)return;const {data,error}=await c.rpc('get_my_learning_dashboard',{p_course_key:'bipolar'});if(error)return;const row=Array.isArray(data)?data[0]:data;if(row)render(row.dashboard||row)}catch(e){}}
async function cloudCompetition(){try{const c=getPlatformClient();if(!c)return;const {data:s}=await c.auth.getSession();const user=s?.session?.user;if(!user)return;const current=await c.rpc('get_current_challenge',{p_course_key:'bipolar'});if(current.error)return;const row=Array.isArray(current.data)?current.data[0]:current.data;if(!row)return;const content=row.content||{},loc=content[en?'en':'fr']||content.fr||content.en||{};const title=document.getElementById('v53ChallengeTitle');if(title)title.textContent=loc.title||T.competitionP;const leader=await c.rpc('get_challenge_leaderboard',{p_challenge_key:row.challenge_key,p_limit:100});if(leader.error)return;const rows=leader.data||[],top=rows[0];const holder=top?.display_name||T.noHolder;const h=document.getElementById('v53Holder'),b=document.getElementById('v53CoatName'),cnt=document.getElementById('v53ChallengerCount');if(h)h.textContent=holder;if(b)b.textContent=holder;if(cnt)cnt.textContent=rows.length>=100?'100+':String(rows.length);const card=document.querySelector('.v53-coat-card'),action=card?.querySelector('.v53-coat-action');const mine=!!top&&top.user_id===user.id;if(card)card.classList.toggle('is-holder',mine);if(action)action.textContent=mine?(en?'Defend my coat':'Défendre ma blouse'):T.open;}catch(e){}}
function installSummary(){if(document.getElementById('v52SummaryModal'))return;const m=document.createElement('div');m.className='modal-backdrop';m.id='v52SummaryModal';m.setAttribute('aria-hidden','true');m.innerHTML=`<section class="modal-card"><div class="modal-head"><div><div class="eyebrow dark">PSYLAB</div><h2>${T.summary}</h2></div><button class="icon-btn" data-v52-close>×</button></div><div class="summary-modal-grid"><div class="summary-modal-box"><b id="v52ModalTrophies">0</b><span>${T.trophies}</span></div><div class="summary-modal-box"><b id="v52ModalScore">0</b><span>${T.score}</span></div></div><div class="row-actions" style="margin-top:16px"><a class="primary-btn" href="${en?'courses/bipolar/en.html#badges':'courses/bipolar/index.html#badges'}">BipolarLab · ${T.trophies}</a></div></section>`;document.body.appendChild(m);m.querySelector('[data-v52-close]').onclick=()=>closeSummary();m.onclick=e=>{if(e.target===m)closeSummary()}}
function openSummary(){installSummary();document.getElementById('v52ModalTrophies').textContent=document.getElementById('totalTrophies')?.textContent||'0';document.getElementById('v52ModalScore').textContent=document.getElementById('globalScore')?.textContent||'0';const m=document.getElementById('v52SummaryModal');m.classList.add('show');m.setAttribute('aria-hidden','false')}
function closeSummary(){const m=document.getElementById('v52SummaryModal');if(m){m.classList.remove('show');m.setAttribute('aria-hidden','true')}}
function fixMobileNav(){const nav=document.querySelector('.mobile-app-nav');if(!nav)return;const items=[...nav.children];const activate=x=>{items.forEach(i=>i.classList.remove('active'));x?.classList.add('active')};const home=nav.querySelector('a[href="#home"]'),labs=nav.querySelector('a[href="#labs"]'),trophy=document.getElementById('mobileTrophies'),profile=document.getElementById('mobileProfile');home?.addEventListener('click',e=>{e.preventDefault();document.getElementById('home')?.scrollIntoView({behavior:'smooth'});activate(home)});labs?.addEventListener('click',e=>{e.preventDefault();document.getElementById('labs')?.scrollIntoView({behavior:'smooth'});activate(labs)});trophy?.addEventListener('click',e=>{e.preventDefault();openSummary();activate(trophy)});profile?.addEventListener('click',e=>{e.preventDefault();const m=document.getElementById('accountModal');if(m){m.classList.add('show');m.setAttribute('aria-hidden','false')}try{if(typeof showPane==='function')showPane('profile')}catch(_){ }activate(profile)})}
function init(){injectActivity();installSummary();fixMobileNav();render(local());setTimeout(()=>{updateResume();cloudDashboard();cloudCompetition()},1000);setInterval(()=>{cloudDashboard();cloudCompetition()},30000);window.addEventListener('storage',e=>{if(['psylabLearningV51','bplabV40','bplabN2V44'].includes(e.key))render(local())})}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();
