(function(){
const q=s=>document.querySelector(s),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function initials(n){return String(n||'R').trim().split(/\s+/).slice(0,2).map(x=>x[0]).join('').toUpperCase()||'R'}
function localMetrics(){try{const s=JSON.parse(localStorage.getItem('bplabV40')||'{}'),n=JSON.parse(localStorage.getItem('bplabN2V44')||'{}');const vals=o=>Object.values(o||{}),dis=vals(s.levels).filter(v=>Number(v)>=2).length,mem=vals(s.memory).filter(v=>v==='solid').length,duels=vals(s.duels).filter(Boolean).length,st=vals(n.stations).filter(v=>v==='acquis').length;return Math.max(0,Math.min(100,Math.round((dis/50*.35+mem/50*.25+Math.min(duels,30)/30*.15+Math.min(st,30)/30*.25)*100)))}catch(_){return 0}}
async function signedAvatar(c,path){if(!path)return'';try{const {data,error}=await c.storage.from('avatars').createSignedUrl(path,3600);return error?'':data?.signedUrl||''}catch(_){return''}}
function pct(ctx,key='bipolar'){const p=(ctx.progress||[]).find(x=>x.course_key===key);const raw=Number(p?.course_score||0);return raw?Math.min(100,Math.round(raw>100?raw/10:raw)):localMetrics()}
function quote(){const lang=window.PsyLabV60.lang(),bank={fr:[['« Lorsque nous ne pouvons plus changer une situation, nous sommes mis au défi de nous changer nous-mêmes. »','Viktor E. Frankl'],['« Le bon médecin traite la maladie ; le grand médecin traite le patient qui a la maladie. »','William Osler'],['« Le curieux paradoxe est que lorsque je m’accepte tel que je suis, alors je peux changer. »','Carl Rogers']],en:[['“When we are no longer able to change a situation, we are challenged to change ourselves.”','Viktor E. Frankl'],['“The good physician treats the disease; the great physician treats the patient who has the disease.”','William Osler'],['“The curious paradox is that when I accept myself just as I am, then I can change.”','Carl Rogers']]};return bank[lang][Math.floor(Date.now()/86400000)%bank[lang].length]}
function setGreeting(ctx){const lang=window.PsyLabV60.lang(),name=ctx.profile?.display_name||ctx.user.user_metadata?.display_name||ctx.user.user_metadata?.full_name||ctx.user.email?.split('@')[0]||(lang==='en'?'User':'Utilisateur'),status=ctx.profile?.professional_status||ctx.profile?.residency_year||'',hour=new Date().getHours(),hello=lang==='en'?(hour>=18?'Good evening':'Hello'):(hour>=18?'Bonsoir':'Bonjour');q('#greeting').innerHTML=`${hello}, <span>${esc(name)}</span> 👋`;q('#userMeta').textContent=[window.PsyLabV60.statusLabel(status),`BipolarLab ${pct(ctx)}%`].filter(Boolean).join(' · ');q('#userName').textContent=name;q('#userSub').textContent=window.PsyLabV60.statusLabel(status);q('#sideName').textContent=name;q('#sideYear').textContent=window.PsyLabV60.statusLabel(status);[q('#topAvatar'),q('#sideAvatar')].forEach(a=>a.textContent=initials(name));signedAvatar(ctx.client,ctx.profile?.avatar_path).then(u=>{if(u)[q('#topAvatar'),q('#sideAvatar')].forEach(a=>a.innerHTML=`<img src="${u}" alt="">`)})}
function renderQuote(){const [t,a]=quote();q('#quoteText').textContent=t;q('#quoteAuthor').textContent='— '+a}
function renderResume(ctx){const p=pct(ctx);q('#resumePct').textContent=p+'%';q('#resumeBar').style.width=p+'%';q('#resumeLink').href=window.PsyLabV60.lang()==='en'?'courses/bipolar/en.html':'courses/bipolar/index.html';q('#resumeTitle').textContent='BipolarLab';q('#resumeLevel').textContent=window.PsyLabV60.lang()==='en'?'Level 1 — Observe':'Niveau 1 — Observer';q('#resumeMission').textContent=window.PsyLabV60.lang()==='en'?'Mission 4 · Thought process':'Mission 4 · Cours de la pensée'}
function renderLabs(ctx){const lang=window.PsyLabV60.lang(),catalog=(window.PSYLAB_COURSES||[]).slice(0,3),box=q('#labsGrid');box.innerHTML=catalog.map(c=>{const active=c.status==='active',pp=active?pct(ctx,c.key):0,href=active?window.PsyLabV60.courseHref(c):'labs.html';return `<a class="ps59-card ps59-labcard" href="${href}"><div class="ps59-labicon">${esc(c.icon||'◌')}</div><div><h3>${esc(lang==='en'?c.title_en:c.title_fr)}</h3><p>${esc(lang==='en'?c.subtitle_en:c.subtitle_fr)}</p><div class="ps59-labfoot"><div class="ps59-labbar"><i style="width:${pp}%"></i></div><span>${active?pp+'%':window.PsyLabV60.tr('coming')}</span></div></div></a>`}).join('')}
function renderMaintenance(ctx){const unlocked=pct(ctx)>=100,card=q('#maintenanceCard'),copy=q('#maintenanceCopy'),lock=q('#maintenanceLock');if(unlocked){card.href='maintenance.html';copy.innerHTML=`<h3>${window.PsyLabV60.tr('maintenance')}</h3><p>${window.PsyLabV60.tr('retention_due')} · 7 min</p>`;lock.textContent='→'}else{card.removeAttribute('href');copy.innerHTML=`<h3>${window.PsyLabV60.tr('maintenance')}</h3><p>${window.PsyLabV60.tr('maintenance_locked')}</p>`;lock.textContent='🔒'}}
async function renderBlouse(ctx){const c=ctx.client,lang=window.PsyLabV60.lang();q('#blouseIntro').textContent=lang==='en'?'A weekly clinical challenge. One ranked attempt. One coat.':'Un défi clinique hebdomadaire. Une tentative classée. Une seule blouse.';try{const current=await c.rpc('get_current_challenge',{p_course_key:'bipolar'}),row=Array.isArray(current.data)?current.data[0]:current.data;if(!row)return;const loc=row.content?.[lang]||row.content?.fr||{};q('#weekCase').textContent=loc.title||(lang==='en'?'The detail that changes everything':'Le détail qui change tout');const lb=await c.rpc('get_challenge_leaderboard',{p_challenge_key:row.challenge_key,p_limit:100}),rows=lb.data||[],top=rows[0];q('#participantCount').textContent=`${rows.length} ${window.PsyLabV60.tr('participants')}`;if(top){q('#holderName').textContent=top.display_name;let pub=null;try{const r=await c.rpc('get_public_profiles',{p_user_ids:[top.user_id]});pub=r.data?.[0]}catch(_){}const st=pub?.professional_status||pub?.residency_year||'';q('#holderMeta').textContent=[window.PsyLabV60.statusLabel(st),lang==='en'?'current holder':'titulaire actuel'].filter(Boolean).join(' · ');q('#holderAvatar').textContent=initials(top.display_name);const u=await signedAvatar(c,pub?.avatar_path);if(u)q('#holderAvatar').innerHTML=`<img src="${u}" alt="">`}const end=new Date(row.ends_at);if(!Number.isNaN(end.getTime())){const rem=Math.max(0,end-Date.now()),d=Math.floor(rem/86400000),h=Math.floor((rem%86400000)/3600000);q('#countdown').textContent=`${d} j ${h} h`}}catch(_){}}
window.addEventListener('psylab:v60-ready',e=>{const ctx=e.detail;setGreeting(ctx);renderQuote();renderResume(ctx);renderLabs(ctx);renderMaintenance(ctx);renderBlouse(ctx)});
})();
