(function(){
const q=s=>document.querySelector(s),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const preview=new URLSearchParams(location.search).get('preview')==='1';
const art={bipolar:'assets/v79/bipolar.jpg',psychosis:'assets/v79/psychose.jpg',anxiety:'assets/v79/anxiete.jpg',addiction:'assets/v79/addicto.jpg'};
const display={fr:{bipolar:['BipolarLab','Trouble bipolaire et apparentés'],psychosis:['PsychoseLab','Spectre de la schizophrénie et autres psychoses'],anxiety:['AnxiétéLab','Troubles anxieux et troubles liés au stress'],addiction:['AddictoLab','Conduites addictives et usages de substances']},en:{bipolar:['BipolarLab','Bipolar and related disorders'],psychosis:['PsychosisLab','Schizophrenia spectrum and other psychoses'],anxiety:['AnxietyLab','Anxiety and stress-related disorders'],addiction:['AddictionLab','Addictive behaviours and substance use']}};
function initials(n){return String(n||'R').trim().split(/\s+/).slice(0,2).map(x=>x[0]).join('').toUpperCase()||'R'}
function pct(ctx,key='bipolar'){if(preview&&key==='bipolar')return 46;const p=(ctx?.progress||[]).find(x=>x.course_key===key),raw=Number(p?.course_score||0);if(raw)return Math.min(100,Math.round(raw>100?raw/10:raw));if(key==='bipolar'){try{const s=JSON.parse(localStorage.getItem('bplabV40')||'{}'),n=JSON.parse(localStorage.getItem('bplabN2V44')||'{}'),vals=o=>Object.values(o||{}),dis=vals(s.levels).filter(v=>Number(v)>=2).length,mem=vals(s.memory).filter(v=>v==='solid').length,duels=vals(s.duels).filter(Boolean).length,st=vals(n.stations).filter(v=>v==='acquis').length;return Math.max(0,Math.min(100,Math.round((dis/50*.35+mem/50*.25+Math.min(duels,30)/30*.15+Math.min(st,30)/30*.25)*100)))}catch(_){}}return 0}
async function signedAvatar(c,path){if(!c||!path)return'';try{const {data,error}=await c.storage.from('avatars').createSignedUrl(path,3600);return error?'':data?.signedUrl||''}catch(_){return''}}
function status(v,lang){v=String(v||'').toUpperCase();if(/^R[1-4]$/.test(v))return v;const fr={EXTERNE:'Externe',INTERNE:'Interne',ASSISTANT:'Assistant',PROFESSEUR:'Professeur'},en={EXTERNE:'Extern',INTERNE:'Intern',ASSISTANT:'Assistant',PROFESSEUR:'Professor'};return (lang==='en'?en:fr)[v]||v}
function renderIdentity(ctx){const lang=window.PsyLabV60?.lang?.()||'fr',name=preview?'Nadia':(ctx?.profile?.display_name||ctx?.user?.user_metadata?.display_name||ctx?.user?.user_metadata?.full_name||ctx?.user?.email?.split('@')[0]||(lang==='en'?'User':'Utilisateur')),st=status(ctx?.profile?.professional_status||ctx?.profile?.residency_year,lang),h=new Date().getHours(),hello=lang==='en'?(h>=18?'Good evening':'Hello'):(h>=18?'Bonsoir':'Bonjour'),p=pct(ctx);if(q('#greeting'))q('#greeting').innerHTML=`${hello} <span>${esc(name)}</span>,`;if(q('#userMeta'))q('#userMeta').textContent=[st,`BipolarLab ${p}%`].filter(Boolean).join(' · ');if(q('#userName'))q('#userName').textContent=name;if(q('#userSub'))q('#userSub').textContent=st;if(q('#topAvatar')){q('#topAvatar').textContent=initials(name);signedAvatar(ctx?.client,ctx?.profile?.avatar_path).then(u=>{if(u&&q('#topAvatar'))q('#topAvatar').innerHTML=`<img src="${u}" alt="">`})}if(q('#resumePct'))q('#resumePct').textContent=p+'%';if(q('#resumeBar'))q('#resumeBar').style.width=p+'%'}
function renderLabs(ctx){const lang=window.PsyLabV60?.lang?.()||'fr',box=q('#labsGrid');if(!box)return;const keys=['bipolar','psychosis','anxiety','addiction'];const previewPct={bipolar:38,psychosis:12,anxiety:0,addiction:0};box.innerHTML=keys.map(key=>{const active=key==='bipolar',p=preview?previewPct[key]:(active?pct(ctx,key):0),labels=display[lang]?.[key]||display.fr[key],href=active?'courses/bipolar/index.html':'labs.html',cta=active?(lang==='en'?'Resume Lab':'Reprendre le Lab'):(lang==='en'?'Start Lab':'Commencer le Lab');return `<a class="ps77-lab" href="${href}"><div class="ps77-lab-visual"><img src="${art[key]}" alt=""></div><div class="ps77-lab-body"><h3>${esc(labels[0])}</h3><p>${esc(labels[1])}</p><div class="ps77-lab-progress"><div class="ps-progress"><i style="width:${p}%"></i></div><strong>${p}%</strong></div><span class="ps77-lab-cta">${esc(cta)} <b>→</b></span></div></a>`}).join('')}
async function vestiaire(ctx){if(preview){q('#participantCount').textContent='126';q('#countdown').textContent='4 j';return}const c=ctx?.client;if(!c)return;try{const current=await c.rpc('get_current_challenge',{p_course_key:'bipolar'}),row=Array.isArray(current.data)?current.data[0]:current.data;if(!row)return;const lb=await c.rpc('get_challenge_leaderboard',{p_challenge_key:row.challenge_key,p_limit:100}),rows=lb.data||[];if(q('#participantCount'))q('#participantCount').textContent=String(rows.length);const end=new Date(row.ends_at);if(!Number.isNaN(end.getTime())){const rem=Math.max(0,end-Date.now()),d=Math.floor(rem/86400000),h=Math.floor((rem%86400000)/3600000);if(q('#countdown'))q('#countdown').textContent=`${d} j ${h} h`}}catch(_){}}
function render(ctx){renderIdentity(ctx);renderLabs(ctx);vestiaire(ctx)}
window.addEventListener('psylab:v60-ready',e=>render(e.detail));
if(preview){document.body.classList.remove('ps59-auth-pending','ps59-auth-required');document.body.classList.add('ps59-authenticated');render({profile:{display_name:'Nadia',professional_status:'R3'},user:{email:'nadia@example.test',user_metadata:{}},progress:[{course_key:'bipolar',course_score:46}]})}
})();
