(function(){
const q=s=>document.querySelector(s);let client,user,profile={};
function initials(n){return String(n||'U').trim().split(/\s+/).slice(0,2).map(x=>x[0]).join('').toUpperCase()||'U'}
async function avatarUrl(path){if(!path)return'';try{const {data,error}=await client.storage.from('avatars').createSignedUrl(path,3600);return error?'':data?.signedUrl||''}catch(_){return''}}
async function showPhoto(path,name){const el=q('#profilePhoto');el.textContent=initials(name);const u=await avatarUrl(path);if(u)el.innerHTML='<img src="'+u+'" alt="Photo de profil">'}
async function compress(file){let img,w0,h0,revoke=null;if('createImageBitmap'in window){img=await createImageBitmap(file);w0=img.width;h0=img.height}else{const u=URL.createObjectURL(file);revoke=u;img=await new Promise((res,rej)=>{const im=new Image();im.onload=()=>res(im);im.onerror=rej;im.src=u});w0=img.naturalWidth;h0=img.naturalHeight}const max=512,scale=Math.min(1,max/Math.max(w0,h0)),w=Math.max(1,Math.round(w0*scale)),h=Math.max(1,Math.round(h0*scale)),cv=document.createElement('canvas');cv.width=w;cv.height=h;cv.getContext('2d').drawImage(img,0,0,w,h);if(revoke)URL.revokeObjectURL(revoke);return await new Promise(res=>cv.toBlob(res,'image/webp',.84))}
async function load(){let {data:p,error}=await client.from('profiles').select('display_name,cohort_code,avatar_path,show_avatar_public,residency_year,professional_status,preferred_language').eq('id',user.id).maybeSingle();if(error){const fb=await client.from('profiles').select('display_name,cohort_code,avatar_path,show_avatar_public,residency_year,preferred_language').eq('id',user.id).maybeSingle();p=fb.data||{};p.professional_status=p.residency_year||null}profile=p||{};const name=profile.display_name||user.user_metadata?.display_name||user.user_metadata?.full_name||user.email?.split('@')[0]||'Utilisateur',status=profile.professional_status||profile.residency_year||'';q('#profileName').textContent=name;q('#profileStatusText').textContent=window.PsyLabV60.statusLabel(status)||'—';q('#profileEmail').textContent=user.email||'—';q('#profilePseudo').value=name;q('#profileStatusSelect').value=status;q('#profileCohortInput').value=profile.cohort_code||'';q('#profileLang').value=profile.preferred_language||window.PsyLabV60.lang();q('#profilePhotoPublic').checked=!!profile.show_avatar_public;await showPhoto(profile.avatar_path,name);const {data:cp}=await client.from('course_progress').select('course_key,course_score,trophy_count').eq('user_id',user.id);const active=(cp||[]).filter(x=>Number(x.course_score||0)>0).length,score=(cp||[]).reduce((a,x)=>a+Number(x.course_score||0),0),trophies=(cp||[]).reduce((a,x)=>a+Number(x.trophy_count||0),0),pct=Math.min(100,Math.round(Number((cp||[]).find(x=>x.course_key==='bipolar')?.course_score||0)/10));q('#kpiLabs').textContent=active;q('#kpiBadges').textContent=trophies;q('#kpiProgress').textContent=pct+'%';q('#profileProgressBar').style.width=pct+'%';q('#profileStatusInline').textContent=window.PsyLabV60.statusLabel(status)||'—';q('#profileCohortText').textContent=profile.cohort_code||'—';q('#profileLanguageText').textContent=(profile.preferred_language||window.PsyLabV60.lang())==='en'?'English':'Français'}
async function save(){const display_name=q('#profilePseudo').value.trim(),professional_status=q('#profileStatusSelect').value||null,cohort_code=q('#profileCohortInput').value.trim().toUpperCase()||null,preferred_language=q('#profileLang').value||'fr',show_avatar_public=q('#profilePhotoPublic').checked;if(display_name.length<2||!professional_status){q('#profileMessage').textContent=window.PsyLabV60.lang()==='en'?'Nickname and professional status are required.':'Le pseudonyme et le statut professionnel sont requis.';return}const residency_year=/^R[1-4]$/.test(professional_status)?professional_status:null;const {error}=await client.from('profiles').update({display_name,professional_status,residency_year,cohort_code,preferred_language,show_avatar_public,updated_at:new Date().toISOString()}).eq('id',user.id);q('#profileMessage').textContent=error?error.message:(window.PsyLabV60.lang()==='en'?'Profile saved.':'Profil enregistré.');if(!error){localStorage.setItem('psylab_lang_v59',preferred_language);setTimeout(()=>location.reload(),350)}}
async function upload(file){if(!file)return;if(!/^image\/(jpeg|png|webp)$/.test(file.type)){q('#profileMessage').textContent='Formats acceptés : JPG, PNG, WebP.';return}if(file.size>8*1024*1024){q('#profileMessage').textContent='Image trop volumineuse.';return}q('#profileMessage').textContent='Préparation de la photo…';const blob=await compress(file),path=`${user.id}/avatar-${Date.now()}.webp`;if(profile.avatar_path)await client.storage.from('avatars').remove([profile.avatar_path]);const {error}=await client.storage.from('avatars').upload(path,blob,{contentType:'image/webp',upsert:true});if(error){q('#profileMessage').textContent=error.message;return}const up=await client.from('profiles').update({avatar_path:path,updated_at:new Date().toISOString()}).eq('id',user.id);q('#profileMessage').textContent=up.error?up.error.message:'Photo mise à jour.';if(!up.error){profile.avatar_path=path;showPhoto(path,q('#profilePseudo').value)}}
async function remove(){if(profile.avatar_path)await client.storage.from('avatars').remove([profile.avatar_path]);await client.from('profiles').update({avatar_path:null,updated_at:new Date().toISOString()}).eq('id',user.id);profile.avatar_path=null;showPhoto('',q('#profilePseudo').value);q('#profileMessage').textContent='Photo retirée.'}
window.addEventListener('psylab:v60-page-ready',e=>{client=e.detail.client;user=e.detail.user;profile=e.detail.profile||{};load()});q('#profileSave').onclick=save;q('#profilePhotoInput').onchange=e=>upload(e.target.files?.[0]);q('#profilePhotoRemove').onclick=remove;q('#profileLogout').onclick=async()=>{await client.auth.signOut();location.replace('index.html')};
})();
