(function(){
const q=s=>document.querySelector(s),set=(id,v)=>{const e=document.getElementById(id);if(e)e.textContent=v};let c,u,p={};
function initials(n){return String(n||'R').trim().split(/\s+/).slice(0,2).map(x=>x[0]).join('').toUpperCase()||'R'}
async function avatarUrl(path){if(!path)return'';try{const {data,error}=await c.storage.from('avatars').createSignedUrl(path,3600);return error?'':(data?.signedUrl||'')}catch(_){return''}}
async function showAvatar(path,name){const el=q('#profileAvatarV56');const url=await avatarUrl(path);el.textContent=initials(name);if(url)el.innerHTML='<img alt="Photo de profil" src="'+url+'">'}
function localLearning(){try{return window.PsyLabLearning?.localAggregate?.('bipolar')||{active_days_7:0,weaknesses:[]}}catch(_){return{active_days_7:0,weaknesses:[]}}}
function skillLabel(k){return({'temporalite.trait_vs_etat':'Temporalité · trait vs état','temporalite.episodicite':'Épisodicité','cours_pensee.vitesse_vs_direction':'Cours de pensée','raisonnement.fermeture_prematuree':'Fermeture prématurée','differentiel.hierarchisation':'Hiérarchisation différentielle','diagnostic.seuil_manie_hypomanie':'Seuil manie / hypomanie','incertitude.surconfiance':'Calibration de confiance','anamnese.information_collaterale':'Information collatérale'})[k]||String(k||'Compétence').replaceAll('_',' ')}
async function compress(file){let img,w0,h0,revoke=null;if('createImageBitmap' in window){img=await createImageBitmap(file);w0=img.width;h0=img.height}else{const url=URL.createObjectURL(file);revoke=url;img=await new Promise((res,rej)=>{const im=new Image();im.onload=()=>res(im);im.onerror=rej;im.src=url});w0=img.naturalWidth;h0=img.naturalHeight}const max=512,scale=Math.min(1,max/Math.max(w0,h0)),w=Math.max(1,Math.round(w0*scale)),h=Math.max(1,Math.round(h0*scale)),cv=document.createElement('canvas');cv.width=w;cv.height=h;cv.getContext('2d').drawImage(img,0,0,w,h);if(revoke)URL.revokeObjectURL(revoke);return await new Promise(res=>cv.toBlob(res,'image/webp',.84))}
async function load(){const {data:s}=await c.auth.getSession();u=s.session?.user;if(!u)return;const {data}=await c.from('profiles').select('display_name,cohort_code,avatar_path,show_avatar_public,residency_year,preferred_language').eq('id',u.id).maybeSingle();p=data||{};const name=p.display_name||u.user_metadata?.display_name||'Résident';set('profileNameV56',name);set('profileResidencyV56',p.residency_year||'Résident');set('profileCohortV56',p.cohort_code?' · '+p.cohort_code:'');q('#profilePseudoV56').value=name;q('#profileCohortInput').value=p.cohort_code||'';q('#profileResidencySelect').value=p.residency_year||'';q('#profileLangSelect').value=p.preferred_language||localStorage.getItem('psylabLang')||'fr';q('#profilePhotoPublic').checked=!!p.show_avatar_public;await showAvatar(p.avatar_path,name);
const {data:cp}=await c.from('course_progress').select('course_score,trophy_count').eq('user_id',u.id);set('profileScoreV56',(cp||[]).reduce((a,x)=>a+Number(x.course_score||0),0));set('achTrophies',(cp||[]).reduce((a,x)=>a+Number(x.trophy_count||0),0));const learn=localLearning();set('profileStreakV56',learn.active_days_7||0);renderSkills(learn.weaknesses||[]);
try{const {data:rank}=await c.rpc('get_platform_leaderboard',{p_cohort:null,p_limit:200});const me=(rank||[]).find(x=>x.user_id===u.id);set('profileRankV56',me?'#'+me.rank:'—')}catch(_){ }
try{const {data:season}=await c.rpc('get_season_leaderboard',{p_course_key:'bipolar',p_limit:200});const me=(season||[]).find(x=>x.user_id===u.id);const wins=Number(me?.coat_wins||0);set('profileCoatsV56',wins);set('achCoats',wins);set('achDefenses',Math.max(0,wins-1));}catch(_){ }
}
function renderSkills(rows){const box=q('#profileSkillsV56');if(!rows.length){box.innerHTML='<div class="ps56-empty">Aucune faiblesse stable détectée. Continuez les activités pour construire votre profil.</div>';return}box.innerHTML=rows.slice(0,8).map(x=>{const m=Math.max(0,Math.min(100,Number(x.mastery??x.mastery_score??0)));return `<div class="ps56-skill-row2"><span>${skillLabel(x.key||x.competency_key)}</span><div class="ps56-bar"><i style="width:${m}%"></i></div><b>${Math.round(m)}%</b></div>`}).join('')}
async function save(){const display_name=q('#profilePseudoV56').value.trim(),cohort_code=q('#profileCohortInput').value.trim().toUpperCase()||null,residency_year=q('#profileResidencySelect').value||null,preferred_language=q('#profileLangSelect').value||'fr',show_avatar_public=q('#profilePhotoPublic').checked;if(display_name.length<3){set('profileMessageV56','Pseudonyme : 3 caractères minimum.');return}const {error}=await c.from('profiles').update({display_name,cohort_code,residency_year,preferred_language,show_avatar_public,updated_at:new Date().toISOString()}).eq('id',u.id);set('profileMessageV56',error?error.message:'Profil enregistré.');if(!error){localStorage.setItem('psylabLang',preferred_language);await load()}}
async function upload(file){if(!file||!u)return;if(!/^image\/(jpeg|png|webp)$/.test(file.type)){set('profileMessageV56','Format accepté : JPG, PNG ou WebP.');return}if(file.size>8*1024*1024){set('profileMessageV56','Image trop volumineuse (8 Mo maximum).');return}set('profileMessageV56','Préparation de la photo…');const blob=await compress(file),path=`${u.id}/avatar-${Date.now()}.webp`;if(p.avatar_path)await c.storage.from('avatars').remove([p.avatar_path]);const {error}=await c.storage.from('avatars').upload(path,blob,{contentType:'image/webp',upsert:true});if(error){set('profileMessageV56',error.message);return}const up=await c.from('profiles').update({avatar_path:path,updated_at:new Date().toISOString()}).eq('id',u.id);if(up.error){set('profileMessageV56',up.error.message);return}p.avatar_path=path;await showAvatar(path,q('#profilePseudoV56').value);set('profileMessageV56','Photo mise à jour.')}
async function remove(){if(p.avatar_path)await c.storage.from('avatars').remove([p.avatar_path]);await c.from('profiles').update({avatar_path:null,updated_at:new Date().toISOString()}).eq('id',u.id);p.avatar_path=null;await showAvatar('',q('#profilePseudoV56').value);set('profileMessageV56','Photo retirée.')}
window.addEventListener('psylab:v56-ready',e=>{c=e.detail.client;u=e.detail.user;p=e.detail.profile||{};load()});q('#saveProfileV56').onclick=save;q('#avatarFile').onchange=e=>upload(e.target.files?.[0]);q('#removeAvatar').onclick=remove;q('#logoutV56').onclick=async()=>{await c.auth.signOut();location.replace('index.html')};
})();
