(function(){
const q=s=>document.querySelector(s),qa=s=>[...document.querySelectorAll(s)];let client,user,profile;
function initials(n){return String(n||'R').trim().split(/\s+/).slice(0,2).map(x=>x[0]).join('').toUpperCase()||'R'}
function label(k){return({'temporalite.trait_vs_etat':'Temporalité · trait vs état','temporalite.episodicite':'Épisodicité','cours_pensee.vitesse_vs_direction':'Cours de pensée · vitesse vs direction','raisonnement.fermeture_prematuree':'Fermeture prématurée','raisonnement.compatible_vs_discriminant':'Compatible vs discriminant','differentiel.hierarchisation':'Hiérarchisation différentielle','diagnostic.seuil_manie_hypomanie':'Seuil manie / hypomanie','incertitude.surconfiance':'Calibration de confiance','anamnese.information_collaterale':'Information collatérale'})[k]||String(k||'Compétence').replaceAll('_',' ')}
async function avatarUrl(path){if(!path)return'';try{const {data,error}=await client.storage.from('avatars').createSignedUrl(path,3600);return error?'':data?.signedUrl||''}catch(_){return''}}
async function showPhoto(path,name){const el=q('#profilePhoto');el.textContent=initials(name);const url=await avatarUrl(path);if(url)el.innerHTML='<img src="'+url+'" alt="Photo de profil">'}
function learning(){try{return window.PsyLabLearning?.localAggregate?.('bipolar')||{active_days_7:0,weaknesses:[]}}catch(_){return{active_days_7:0,weaknesses:[]}}}
async function compress(file){let img,w0,h0,revoke=null;if('createImageBitmap'in window){img=await createImageBitmap(file);w0=img.width;h0=img.height}else{const u=URL.createObjectURL(file);revoke=u;img=await new Promise((res,rej)=>{const im=new Image();im.onload=()=>res(im);im.onerror=rej;im.src=u});w0=img.naturalWidth;h0=img.naturalHeight}const max=512,scale=Math.min(1,max/Math.max(w0,h0)),w=Math.max(1,Math.round(w0*scale)),h=Math.max(1,Math.round(h0*scale)),cv=document.createElement('canvas');cv.width=w;cv.height=h;cv.getContext('2d').drawImage(img,0,0,w,h);if(revoke)URL.revokeObjectURL(revoke);return await new Promise(res=>cv.toBlob(res,'image/webp',.84))}
function renderTabs(){qa('[data-profile-tab]').forEach(b=>b.onclick=()=>{qa('[data-profile-tab]').forEach(x=>x.classList.toggle('active',x===b));qa('[data-profile-pane]').forEach(x=>x.classList.toggle('active',x.dataset.profilePane===b.dataset.profileTab))})}
async function load(){const {data:p}=await client.from('profiles').select('display_name,cohort_code,avatar_path,show_avatar_public,residency_year,preferred_language').eq('id',user.id).maybeSingle();profile=p||{};const name=profile.display_name||user.user_metadata?.display_name||'Résident';q('#profileName').textContent=name;q('#profileYear').textContent=profile.residency_year||'Résident';q('#profileCohort').textContent=profile.cohort_code?' · '+profile.cohort_code:'';q('#profilePseudo').value=name;q('#profileYearSelect').value=['R1','R2','R3','R4'].includes(profile.residency_year)?profile.residency_year:'';q('#profileCohortInput').value=profile.cohort_code||'';q('#profileLang').value=profile.preferred_language||'fr';q('#profilePhotoPublic').checked=!!profile.show_avatar_public;await showPhoto(profile.avatar_path,name);
const {data:cp}=await client.from('course_progress').select('course_key,course_score,trophy_count').eq('user_id',user.id);const score=(cp||[]).reduce((a,x)=>a+Number(x.course_score||0),0),trophies=(cp||[]).reduce((a,x)=>a+Number(x.trophy_count||0),0);q('#profileScore').textContent=score;q('#profileTrophies').textContent=trophies;q('#profileLabs').innerHTML=(window.PSYLAB_COURSES||[]).slice(0,4).map(c=>{const p=(cp||[]).find(x=>x.course_key===c.key),pct=c.status==='active'?Math.round(Number(p?.course_score||0)/10):0;return `<div class="v57-activity-row"><i>${c.icon||'◌'}</i><div><b>${c.title_fr}</b><small>${c.status==='active'?pct+'% de progression':'Bientôt disponible'}</small></div><time>${c.status==='active'?'→':'—'}</time></div>`}).join('');
const l=learning();q('#profileStreakBadge').textContent=`${l.active_days_7||0} jour${Number(l.active_days_7||0)>1?'s':''} actif${Number(l.active_days_7||0)>1?'s':''}`;q('#profileSummary').innerHTML=`<div class="v57-activity-row"><i>▣</i><div><b>${(cp||[]).filter(x=>Number(x.course_score)>0).length} Lab(s) commencé(s)</b><small>Votre progression reste commune à toute la plateforme.</small></div></div><div class="v57-activity-row"><i>◎</i><div><b>${(l.weaknesses||[]).length} axe(s) de révision</b><small>Seuls les profils d’erreur suffisamment stables sont affichés.</small></div></div>`;const skills=q('#profileSkills');if((l.weaknesses||[]).length)skills.innerHTML=(l.weaknesses||[]).slice(0,8).map(x=>{const m=Math.max(0,Math.min(100,Number(x.mastery??x.mastery_score??0)));return `<div class="v57-skill"><span>${label(x.key||x.competency_key)}</span><div class="bar"><i style="width:${m}%"></i></div><b>${Math.round(m)}%</b></div>`}).join('');
try{const {data:season}=await client.rpc('get_season_leaderboard',{p_course_key:'bipolar',p_limit:200}),me=(season||[]).find(x=>x.user_id===user.id),coats=Number(me?.coat_wins||0);q('#profileCoats').textContent=coats;q('#profileCoatBadge').textContent=`🥼 ${coats} Blouse${coats>1?'s':''}`;q('#profileAwards').innerHTML=`<div class="v57-activity-row"><i>♛</i><div><b>${coats} Blouse${coats>1?'s':''} remportée${coats>1?'s':''}</b><small>Compétition hebdomadaire</small></div></div><div class="v57-activity-row"><i>🏆</i><div><b>Blouse d’Or</b><small>${Number(me?.season_score||0)>0?'Saison en cours':'Aucune saison remportée'}</small></div></div>`}catch(_){}
try{const {data:rank}=await client.rpc('get_platform_leaderboard',{p_cohort:null,p_limit:200}),me=(rank||[]).find(x=>x.user_id===user.id);q('#profileRankBadge').textContent=me?`Rang actuel #${me.rank}`:'Rang —'}catch(_){}
}
async function save(){const display_name=q('#profilePseudo').value.trim(),cohort_code=q('#profileCohortInput').value.trim().toUpperCase()||null,residency_year=q('#profileYearSelect').value||null,preferred_language=q('#profileLang').value||'fr',show_avatar_public=q('#profilePhotoPublic').checked;if(display_name.length<3){q('#profileMessage').textContent='Pseudonyme : 3 caractères minimum.';return}const {error}=await client.from('profiles').update({display_name,cohort_code,residency_year,preferred_language,show_avatar_public,updated_at:new Date().toISOString()}).eq('id',user.id);q('#profileMessage').textContent=error?error.message:'Profil enregistré.';if(!error)load()}
async function upload(file){if(!file)return;if(!/^image\/(jpeg|png|webp)$/.test(file.type)){q('#profileMessage').textContent='Formats acceptés : JPG, PNG, WebP.';return}if(file.size>8*1024*1024){q('#profileMessage').textContent='Image trop volumineuse.';return}q('#profileMessage').textContent='Préparation de la photo…';const blob=await compress(file),path=`${user.id}/avatar-${Date.now()}.webp`;if(profile.avatar_path)await client.storage.from('avatars').remove([profile.avatar_path]);const {error}=await client.storage.from('avatars').upload(path,blob,{contentType:'image/webp',upsert:true});if(error){q('#profileMessage').textContent=error.message;return}const up=await client.from('profiles').update({avatar_path:path,updated_at:new Date().toISOString()}).eq('id',user.id);q('#profileMessage').textContent=up.error?up.error.message:'Photo mise à jour.';if(!up.error){profile.avatar_path=path;showPhoto(path,q('#profilePseudo').value)}}
async function remove(){if(profile.avatar_path)await client.storage.from('avatars').remove([profile.avatar_path]);await client.from('profiles').update({avatar_path:null,updated_at:new Date().toISOString()}).eq('id',user.id);profile.avatar_path=null;showPhoto('',q('#profilePseudo').value);q('#profileMessage').textContent='Photo retirée.'}
window.addEventListener('psylab:v57-page-ready',e=>{client=e.detail.client;user=e.detail.user;profile=e.detail.profile||{};load()});renderTabs();q('#profileSave').onclick=save;q('#profilePhotoInput').onchange=e=>upload(e.target.files?.[0]);q('#profilePhotoRemove').onclick=remove;q('#profileLogout').onclick=async()=>{await client.auth.signOut();location.replace('index.html')};
})();
