-- PsyLab V51 — migration learning analytics + adaptive mastery + maintenance + weekly challenges
-- Run AFTER supabase_schema_v50.sql in Supabase SQL Editor.
-- Stores pedagogical interaction data only. Do not store patient-identifiable information.

create table if not exists public.learning_events (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  course_key text not null check (course_key ~ '^[a-z0-9_-]{2,40}$'),
  activity_key text not null,
  competency_key text not null,
  event_type text not null,
  is_correct boolean null,
  answer_code text null,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);
create index if not exists learning_events_user_course_time_idx on public.learning_events(user_id,course_key,created_at desc);
create index if not exists learning_events_course_comp_idx on public.learning_events(course_key,competency_key,created_at desc);

create table if not exists public.skill_mastery (
  user_id uuid not null references auth.users(id) on delete cascade,
  course_key text not null,
  competency_key text not null,
  attempts integer not null default 0,
  correct_count integer not null default 0,
  error_count integer not null default 0,
  mastery_score numeric(5,2) not null default 50 check (mastery_score between 0 and 100),
  last_seen timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  primary key(user_id,course_key,competency_key)
);
create index if not exists skill_mastery_user_course_score_idx on public.skill_mastery(user_id,course_key,mastery_score asc);

create table if not exists public.study_sessions (
  session_id uuid primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  course_key text not null,
  started_at timestamptz not null default now(),
  last_active_at timestamptz not null default now(),
  active_seconds integer not null default 0 check (active_seconds between 0 and 86400),
  event_count integer not null default 0 check (event_count between 0 and 10000)
);
create index if not exists study_sessions_user_course_time_idx on public.study_sessions(user_id,course_key,started_at desc);

create table if not exists public.maintenance_reviews (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  course_key text not null,
  score integer not null check (score between 0 and 100),
  item_count integer not null default 0,
  completed_at timestamptz not null default now()
);
create index if not exists maintenance_reviews_user_course_idx on public.maintenance_reviews(user_id,course_key,completed_at desc);

-- Challenge templates are private. Users receive content through an RPC; answer keys are never granted directly.
create table if not exists public.challenge_templates (
  template_id integer primary key,
  course_key text not null,
  content jsonb not null,
  answer_key jsonb not null,
  max_score integer not null default 100
);

create table if not exists public.challenge_attempts (
  user_id uuid not null references auth.users(id) on delete cascade,
  challenge_key text not null,
  course_key text not null,
  score integer not null check (score between 0 and 100),
  answers jsonb not null default '[]'::jsonb,
  submitted_at timestamptz not null default now(),
  primary key(user_id,challenge_key)
);
create index if not exists challenge_attempts_key_score_idx on public.challenge_attempts(challenge_key,score desc);

-- Optional administrator allow-list. Keep it private.
create table if not exists public.platform_admins (
  user_id uuid primary key references auth.users(id) on delete cascade,
  created_at timestamptz not null default now()
);

alter table public.learning_events enable row level security;
alter table public.skill_mastery enable row level security;
alter table public.study_sessions enable row level security;
alter table public.maintenance_reviews enable row level security;
alter table public.challenge_templates enable row level security;
alter table public.challenge_attempts enable row level security;
alter table public.platform_admins enable row level security;

-- Own-data policies.
drop policy if exists "learning_events_select_own" on public.learning_events;
create policy "learning_events_select_own" on public.learning_events for select to authenticated using (auth.uid()=user_id);
drop policy if exists "skill_mastery_select_own" on public.skill_mastery;
create policy "skill_mastery_select_own" on public.skill_mastery for select to authenticated using (auth.uid()=user_id);
drop policy if exists "study_sessions_select_own" on public.study_sessions;
create policy "study_sessions_select_own" on public.study_sessions for select to authenticated using (auth.uid()=user_id);
drop policy if exists "maintenance_reviews_select_own" on public.maintenance_reviews;
create policy "maintenance_reviews_select_own" on public.maintenance_reviews for select to authenticated using (auth.uid()=user_id);
drop policy if exists "challenge_attempts_select_own" on public.challenge_attempts;
create policy "challenge_attempts_select_own" on public.challenge_attempts for select to authenticated using (auth.uid()=user_id);

-- Record one pedagogical event and update the user's adaptive mastery estimate.
create or replace function public.record_learning_event(
  p_course_key text,
  p_activity_key text,
  p_competency_key text,
  p_event_type text,
  p_is_correct boolean default null,
  p_answer_code text default null,
  p_metadata jsonb default '{}'::jsonb
) returns jsonb
language plpgsql security definer set search_path=public as $$
declare
  v_uid uuid:=auth.uid();
  v_old numeric;
  v_new numeric;
begin
  if v_uid is null then raise exception 'Authentication required'; end if;
  if p_course_key is null or p_competency_key is null then raise exception 'Invalid event'; end if;
  if pg_column_size(coalesce(p_metadata,'{}'::jsonb)) > 12000 then raise exception 'Event metadata too large'; end if;

  insert into public.learning_events(user_id,course_key,activity_key,competency_key,event_type,is_correct,answer_code,metadata)
  values(v_uid,left(p_course_key,40),left(coalesce(p_activity_key,'unknown'),160),left(p_competency_key,120),left(coalesce(p_event_type,'attempt'),80),p_is_correct,left(p_answer_code,200),coalesce(p_metadata,'{}'::jsonb));

  if p_is_correct is not null then
    select mastery_score into v_old from public.skill_mastery where user_id=v_uid and course_key=p_course_key and competency_key=p_competency_key;
    if v_old is null then v_old:=case when p_is_correct then 60 else 40 end;
    else
      if p_is_correct then v_old:=v_old + (100-v_old)*0.22;
      else v_old:=v_old - v_old*0.30;
      end if;
    end if;
    v_new:=greatest(0,least(100,v_old));
    insert into public.skill_mastery(user_id,course_key,competency_key,attempts,correct_count,error_count,mastery_score,last_seen,updated_at)
    values(v_uid,p_course_key,p_competency_key,1,case when p_is_correct then 1 else 0 end,case when p_is_correct then 0 else 1 end,v_new,now(),now())
    on conflict(user_id,course_key,competency_key) do update set
      attempts=public.skill_mastery.attempts+1,
      correct_count=public.skill_mastery.correct_count+case when p_is_correct then 1 else 0 end,
      error_count=public.skill_mastery.error_count+case when p_is_correct then 0 else 1 end,
      mastery_score=v_new,
      last_seen=now(),updated_at=now();
  end if;
  return jsonb_build_object('ok',true,'mastery',v_new);
end;$$;
revoke all on function public.record_learning_event(text,text,text,text,boolean,text,jsonb) from public;
grant execute on function public.record_learning_event(text,text,text,text,boolean,text,jsonb) to authenticated;

create or replace function public.touch_study_session(
  p_session_id uuid,
  p_course_key text,
  p_active_seconds integer,
  p_event_count integer
) returns jsonb
language plpgsql security definer set search_path=public as $$
declare v_uid uuid:=auth.uid();
begin
  if v_uid is null then raise exception 'Authentication required'; end if;
  insert into public.study_sessions(session_id,user_id,course_key,started_at,last_active_at,active_seconds,event_count)
  values(p_session_id,v_uid,left(p_course_key,40),now(),now(),greatest(0,least(coalesce(p_active_seconds,0),86400)),greatest(0,least(coalesce(p_event_count,0),10000)))
  on conflict(session_id) do update set
    last_active_at=now(),
    active_seconds=greatest(public.study_sessions.active_seconds,excluded.active_seconds),
    event_count=greatest(public.study_sessions.event_count,excluded.event_count)
  where public.study_sessions.user_id=v_uid;
  return jsonb_build_object('ok',true);
end;$$;
revoke all on function public.touch_study_session(uuid,text,integer,integer) from public;
grant execute on function public.touch_study_session(uuid,text,integer,integer) to authenticated;

create or replace function public.get_my_learning_dashboard(p_course_key text default 'bipolar')
returns table(dashboard jsonb)
language sql security definer set search_path=public as $$
with me as(select auth.uid() uid),
agg as(
 select
  (select count(distinct date(s.started_at)) from public.study_sessions s,me where s.user_id=me.uid and s.course_key=p_course_key and s.started_at>=now()-interval '7 days' and s.active_seconds>0) active_days_7,
  (select count(distinct date(s.started_at)) from public.study_sessions s,me where s.user_id=me.uid and s.course_key=p_course_key and s.started_at>=now()-interval '30 days' and s.active_seconds>0) active_days_30,
  (select coalesce(sum(s.active_seconds),0) from public.study_sessions s,me where s.user_id=me.uid and s.course_key=p_course_key and s.started_at>=now()-interval '30 days') active_seconds_30,
  (select count(*) from public.learning_events e,me where e.user_id=me.uid and e.course_key=p_course_key and e.created_at>=now()-interval '30 days') event_count_30,
  (select case when count(*) filter(where e.is_correct is not null)=0 then null else round(100.0*count(*) filter(where e.is_correct=true)/count(*) filter(where e.is_correct is not null),1) end from public.learning_events e,me where e.user_id=me.uid and e.course_key=p_course_key and e.created_at>=now()-interval '30 days') accuracy_30
), weak as(
 select coalesce(jsonb_agg(jsonb_build_object('key',x.competency_key,'mastery',round(x.mastery_score),'attempts',x.attempts,'errors',x.error_count) order by x.mastery_score asc,x.error_count desc),'[]'::jsonb) weaknesses
 from (select s.* from public.skill_mastery s,me where s.user_id=me.uid and s.course_key=p_course_key order by s.mastery_score asc,s.error_count desc limit 8) x
), rev as(
 select coalesce(jsonb_agg(jsonb_build_object('at',r.completed_at,'score',r.score) order by r.completed_at),'[]'::jsonb) reviews
 from (select r.* from public.maintenance_reviews r,me where r.user_id=me.uid and r.course_key=p_course_key order by r.completed_at desc limit 24) r
)
select jsonb_build_object('active_days_7',agg.active_days_7,'active_days_30',agg.active_days_30,'active_seconds_30',agg.active_seconds_30,'event_count_30',agg.event_count_30,'accuracy_30',agg.accuracy_30,'weaknesses',weak.weaknesses,'maintenance',jsonb_build_object('reviews',rev.reviews)) from agg,weak,rev;
$$;
revoke all on function public.get_my_learning_dashboard(text) from public;
grant execute on function public.get_my_learning_dashboard(text) to authenticated;

create or replace function public.save_maintenance_review(p_course_key text,p_score integer,p_item_count integer default 0)
returns jsonb language plpgsql security definer set search_path=public as $$
declare v_uid uuid:=auth.uid();begin
 if v_uid is null then raise exception 'Authentication required'; end if;
 insert into public.maintenance_reviews(user_id,course_key,score,item_count) values(v_uid,p_course_key,greatest(0,least(p_score,100)),greatest(0,p_item_count));
 return jsonb_build_object('ok',true);
end;$$;
revoke all on function public.save_maintenance_review(text,integer,integer) from public;
grant execute on function public.save_maintenance_review(text,integer,integer) to authenticated;

-- Four rotating BipolarLab challenge templates. Content is bilingual; answer keys remain private.
insert into public.challenge_templates(template_id,course_key,content,answer_key,max_score) values
(1,'bipolar',
 '{"fr":{"title":"Le détail qui change l’arbre","intro":"Cinq décisions. Une seule tentative classée. Pour chaque réponse, indiquez aussi votre niveau de confiance.","questions":[{"prompt":"Un patient dort quatre heures depuis dix jours, se lève spontanément et ne ressent pas la fatigue qu’il aurait habituellement. Quelle donnée porte le plus de poids ?","choices":["Le nombre absolu d’heures","La réduction du besoin de sommeil par rapport au baseline","Le fait de travailler tôt"]},{"prompt":"Le tableau apparaît après une période de stress professionnel réel. Quelle conclusion est la plus rigoureuse ?","choices":["Le stress explique nécessairement tout le syndrome","Le stress peut être un contexte ou déclencheur sans suffire à expliquer le changement qualitatif","Le stress n’a aucune valeur clinique"]},{"prompt":"La pensée est rapide mais le patient reste orienté vers la question. Quel terme est le plus précis ?","choices":["Fuite des idées","Tachypsychie","Tangentialité"]},{"prompt":"Une période d’activation de cinq jours entraîne un changement observable sans altération marquée du fonctionnement. Quel seuil est le plus soutenu ?","choices":["Hypomanie","Manie","Cyclothymie"]},{"prompt":"Un dépistage de bipolarité est positif chez un patient déprimé. Quelle suite est correcte ?","choices":["Le diagnostic bipolaire est confirmé","L’anamnèse longitudinale reste nécessaire","La dépression est exclue"]}]},"en":{"title":"The detail that changes the tree","intro":"Five decisions. One ranked attempt. For each answer, also report your confidence.","questions":[{"prompt":"A patient has slept four hours for ten days, wakes spontaneously and lacks the fatigue normally expected. Which datum carries the most weight?","choices":["The absolute number of hours","Reduced need for sleep relative to baseline","Working early in the morning"]},{"prompt":"The presentation follows a period of genuine occupational stress. What is the most rigorous conclusion?","choices":["Stress necessarily explains the whole syndrome","Stress may be context or trigger without sufficiently explaining the qualitative change","Stress has no clinical value"]},{"prompt":"Thinking is rapid but the patient remains goal-directed. Which term is most precise?","choices":["Flight of ideas","Tachypsychia","Tangentiality"]},{"prompt":"A five-day activation period causes an observable change without marked functional impairment. Which threshold is best supported?","choices":["Hypomania","Mania","Cyclothymia"]},{"prompt":"A bipolarity screen is positive in a depressed patient. What follows?","choices":["Bipolar diagnosis is confirmed","Longitudinal assessment remains necessary","Depression is excluded"]}]}}'::jsonb,
 '{"correct":[1,1,1,0,1]}'::jsonb,100),
(2,'bipolar',
 '{"fr":{"title":"Compatible n’est pas discriminant","intro":"Pesez les données plutôt que de compter les symptômes.","questions":[{"prompt":"Distractibilité actuelle + fonctionnement prémorbide stable + début épisodique à 37 ans : quelle branche perd le plus de poids ?","choices":["TDAH primaire","Épisode thymique","Cause médicale"]},{"prompt":"Une absence de psychose suffit-elle à classer une activation comme hypomanie ?","choices":["Oui","Non, le retentissement fonctionnel et la sévérité comptent aussi","Oui si le sommeil est réduit"]},{"prompt":"Une patiente a un épisode dépressif actuel et un épisode hypomaniaque passé suffisamment caractérisé, sans manie retrouvée. Architecture ?","choices":["Trouble bipolaire I","Trouble bipolaire II","Trouble cyclothymique"]},{"prompt":"Quel énoncé décrit le mieux une fermeture prématurée ?","choices":["Conserver plusieurs hypothèses tant que les données manquent","Conclure dès qu’une explication plausible apparaît sans tester ses concurrentes","Demander une information collatérale"]},{"prompt":"Après amélioration symptomatique, le fonctionnement professionnel reste altéré. Que faut-il faire ?","choices":["Considérer le patient complètement rétabli","Mesurer séparément le fonctionnement","Augmenter le score maniaque"]}]},"en":{"title":"Compatible is not discriminating","intro":"Weight the evidence rather than counting symptoms.","questions":[{"prompt":"Current distractibility + stable premorbid functioning + episodic onset at age 37: which branch loses the most weight?","choices":["Primary ADHD","Mood episode","Medical cause"]},{"prompt":"Is absence of psychosis sufficient to classify activation as hypomania?","choices":["Yes","No; functional impairment and overall severity also matter","Yes if sleep is reduced"]},{"prompt":"A patient has a current major depressive episode and a sufficiently characterized past hypomanic episode, with no mania found. Architecture?","choices":["Bipolar I disorder","Bipolar II disorder","Cyclothymic disorder"]},{"prompt":"Which statement best describes premature closure?","choices":["Keeping multiple hypotheses open while data are missing","Concluding once one plausible explanation appears without testing competitors","Seeking collateral information"]},{"prompt":"After symptomatic improvement, occupational functioning remains impaired. What should be done?","choices":["Consider the patient fully recovered","Measure functioning separately","Increase the mania score"]}]}}'::jsonb,
 '{"correct":[0,1,1,1,1]}'::jsonb,100),
(3,'bipolar',
 '{"fr":{"title":"Chronologie sous pression","intro":"Le Staff vous donne des données vraies, mais pas nécessairement causales.","questions":[{"prompt":"La consommation de café augmente après le début d’une réduction du besoin de sommeil. Quelle interprétation est la plus solide ?","choices":["Cause primaire du début","Peut amplifier le tableau mais explique mal son début","Sans aucune pertinence"]},{"prompt":"Un épisode maniaque ancien est documenté ; l’épisode actuel est dépressif. Quel diagnostic longitudinal reste structurant ?","choices":["Trouble bipolaire I","Trouble bipolaire II","Trouble dépressif majeur"]},{"prompt":"Dans une dépression, des symptômes d’activation apparaissent simultanément sans période hypomaniaque distincte. Que devez-vous évaluer ?","choices":["Une possible mixité","Une hypomanie distincte certaine","Uniquement l’anxiété"]},{"prompt":"Une information rétrospective est plausible mais insuffisamment caractérisée. Que faire ?","choices":["La transformer en épisode certain","La garder comme antécédent possible avec niveau d’incertitude explicite","L’effacer du dossier"]},{"prompt":"Quel outil est le plus adapté pour quantifier la sévérité maniaque au cours du suivi ?","choices":["YMRS","MDQ","WHODAS 2.0"]}]},"en":{"title":"Chronology under pressure","intro":"The Staff gives you true data, but not necessarily causal data.","questions":[{"prompt":"Caffeine intake rises after reduced need for sleep has already begun. Which interpretation is strongest?","choices":["Primary cause of onset","May amplify the presentation but poorly explains its onset","Completely irrelevant"]},{"prompt":"A past manic episode is documented; the current episode is depressive. Which longitudinal diagnosis remains structuring?","choices":["Bipolar I disorder","Bipolar II disorder","Major depressive disorder"]},{"prompt":"During depression, activation symptoms occur concurrently without a distinct hypomanic period. What should be assessed?","choices":["Possible mixed features","Definite distinct hypomania","Anxiety only"]},{"prompt":"A retrospective episode is plausible but insufficiently characterized. What should you do?","choices":["Convert it into a certain episode","Keep it as a possible history with explicit uncertainty","Delete it from the history"]},{"prompt":"Which tool is most appropriate to quantify manic symptom severity over follow-up?","choices":["YMRS","MDQ","WHODAS 2.0"]}]}}'::jsonb,
 '{"correct":[1,0,0,1,0]}'::jsonb,100),
(4,'bipolar',
 '{"fr":{"title":"Le bon doute","intro":"Ce dossier récompense la calibration : savoir conclure, mais aussi savoir ne pas conclure trop tôt.","questions":[{"prompt":"Premier épisode d’activation chez un adulte sans antécédent connu : quelle branche doit rester systématiquement considérée ?","choices":["Causes secondaires / substances / médicaments","Uniquement un trouble bipolaire primaire","Aucune autre branche"]},{"prompt":"Le patient reconnaît qu’il a changé mais continue des décisions risquées malgré leurs conséquences. Quel domaine est spécifiquement altéré ?","choices":["Insight uniquement","Jugement","Attention"]},{"prompt":"Une réponse longue finit par répondre exactement à la question. Quel phénomène ?","choices":["Tangentialité","Circonstancialité","Fuite des idées"]},{"prompt":"Un score MADRS baisse nettement au suivi. Quelle conclusion est valide ?","choices":["Le diagnostic bipolaire est confirmé","La sévérité dépressive mesurée a diminué","Le fonctionnement est nécessairement normalisé"]},{"prompt":"Vous ne disposez pas d’assez d’éléments pour classer un ancien épisode d’activation. Formulation ?","choices":["Épisode hypomaniaque certain","Période d’activation possible, insuffisamment caractérisée","Aucune valeur clinique"]}]},"en":{"title":"The right doubt","intro":"This case rewards calibration: knowing when to conclude, and when not to conclude too early.","questions":[{"prompt":"First activation episode in an adult with no known history: which branch must remain systematically considered?","choices":["Secondary / substance / medication causes","Primary bipolar disorder only","No other branch"]},{"prompt":"The patient recognizes that he has changed but continues risky decisions despite consequences. Which domain is specifically impaired?","choices":["Insight only","Judgment","Attention"]},{"prompt":"A long answer eventually gives exactly the requested information. Which phenomenon?","choices":["Tangentiality","Circumstantiality","Flight of ideas"]},{"prompt":"MADRS falls substantially during follow-up. Which conclusion is valid?","choices":["Bipolar diagnosis is confirmed","Measured depressive severity has decreased","Functioning has necessarily normalized"]},{"prompt":"There is insufficient evidence to classify a past activation period. Best formulation?","choices":["Definite hypomanic episode","Possible activation period, insufficiently characterized","No clinical value"]}]}}'::jsonb,
 '{"correct":[0,1,1,1,1]}'::jsonb,100)
on conflict(template_id) do update set content=excluded.content,answer_key=excluded.answer_key,max_score=excluded.max_score,course_key=excluded.course_key;

create or replace function public.get_current_challenge(p_course_key text default 'bipolar')
returns table(challenge_key text,starts_at timestamptz,ends_at timestamptz,content jsonb)
language plpgsql security definer set search_path=public as $$
declare v_count int;v_id int;v_start timestamptz;v_content jsonb;
begin
 if auth.uid() is null then raise exception 'Authentication required'; end if;
 select count(*) into v_count from public.challenge_templates where course_key=p_course_key;
 if v_count=0 then return; end if;
 v_start:=date_trunc('week',now());
 v_id:=(extract(week from v_start)::int % v_count)+1;
 select c.content into v_content from public.challenge_templates c where c.course_key=p_course_key and c.template_id=v_id;
 challenge_key:=p_course_key||'-'||to_char(v_start,'IYYY-IW');starts_at:=v_start;ends_at:=v_start+interval '7 days';content:=v_content;return next;
end;$$;
revoke all on function public.get_current_challenge(text) from public;
grant execute on function public.get_current_challenge(text) to authenticated;

create or replace function public.submit_weekly_challenge(p_challenge_key text,p_answers jsonb)
returns table(score integer,accepted boolean)
language plpgsql security definer set search_path=public as $$
declare
 v_uid uuid:=auth.uid();v_start timestamptz:=date_trunc('week',now());v_expected_key text;v_count int;v_id int;v_key jsonb;v_i int;v_choice int;v_correct int;v_conf int;v_score int:=0;v_existing int;
begin
 if v_uid is null then raise exception 'Authentication required'; end if;
 select count(*) into v_count from public.challenge_templates where course_key='bipolar';
 if v_count=0 then raise exception 'No challenge template'; end if;
 v_id:=(extract(week from v_start)::int % v_count)+1;v_expected_key:='bipolar-'||to_char(v_start,'IYYY-IW');
 if p_challenge_key<>v_expected_key then raise exception 'Challenge is not current'; end if;
 select answer_key into v_key from public.challenge_templates where course_key='bipolar' and template_id=v_id;
 if jsonb_typeof(p_answers)<>'array' or jsonb_array_length(p_answers)<>jsonb_array_length(v_key->'correct') then raise exception 'Incomplete challenge'; end if;
 select ca.score into v_existing from public.challenge_attempts ca where ca.user_id=v_uid and ca.challenge_key=p_challenge_key;
 if v_existing is not null then score:=v_existing;accepted:=false;return next;return;end if;
 for v_i in 0..jsonb_array_length(p_answers)-1 loop
   v_choice:=coalesce((p_answers->v_i->>'choice')::int,-1);v_conf:=greatest(0,least(coalesce((p_answers->v_i->>'confidence')::int,70),100));v_correct:=(v_key->'correct'->>v_i)::int;
   if v_choice=v_correct then
     v_score:=v_score+16;
     v_score:=v_score+case when v_conf>=85 then 4 when v_conf>=65 then 3 else 2 end;
   else
     v_score:=v_score+case when v_conf<=55 then 4 when v_conf<=75 then 2 else 0 end;
   end if;
 end loop;
 v_score:=greatest(0,least(v_score,100));
 insert into public.challenge_attempts(user_id,challenge_key,course_key,score,answers) values(v_uid,p_challenge_key,'bipolar',v_score,p_answers);
 score:=v_score;accepted:=true;return next;
end;$$;
revoke all on function public.submit_weekly_challenge(text,jsonb) from public;
grant execute on function public.submit_weekly_challenge(text,jsonb) to authenticated;

create or replace function public.get_challenge_leaderboard(p_challenge_key text,p_limit integer default 20)
returns table(rank bigint,user_id uuid,display_name text,cohort_code text,score integer,submitted_at timestamptz)
language sql security definer set search_path=public as $$
with base as(
 select ca.user_id,p.display_name,p.cohort_code,ca.score,ca.submitted_at
 from public.challenge_attempts ca join public.profiles p on p.id=ca.user_id
 where ca.challenge_key=p_challenge_key
), ranked as(
 select rank() over(order by score desc) rank,* from base
)
select r.rank,r.user_id,r.display_name,r.cohort_code,r.score,r.submitted_at from ranked r order by r.rank,r.display_name limit greatest(1,least(coalesce(p_limit,20),100));
$$;
revoke all on function public.get_challenge_leaderboard(text,integer) from public;
grant execute on function public.get_challenge_leaderboard(text,integer) to authenticated;

-- Admin analytics. Add your own auth.users UUID to platform_admins manually after testing.
create or replace function public.get_admin_course_analytics(p_course_key text default 'bipolar',p_days integer default 30)
returns table(analytics jsonb)
language plpgsql security definer set search_path=public as $$
declare v_uid uuid:=auth.uid();v_since timestamptz:=now()-make_interval(days=>greatest(1,least(coalesce(p_days,30),365)));v_result jsonb;
begin
 if v_uid is null or not exists(select 1 from public.platform_admins a where a.user_id=v_uid) then raise exception 'Administrator access required'; end if;
 select jsonb_build_object(
  'active_users', (select count(distinct s.user_id) from public.study_sessions s where s.course_key=p_course_key and s.started_at>=v_since and s.active_seconds>0),
  'sessions', (select count(*) from public.study_sessions s where s.course_key=p_course_key and s.started_at>=v_since and s.active_seconds>0),
  'active_seconds', (select coalesce(sum(s.active_seconds),0) from public.study_sessions s where s.course_key=p_course_key and s.started_at>=v_since),
  'events', (select count(*) from public.learning_events e where e.course_key=p_course_key and e.created_at>=v_since),
  'accuracy', (select case when count(*) filter(where e.is_correct is not null)=0 then null else round(100.0*count(*) filter(where e.is_correct=true)/count(*) filter(where e.is_correct is not null),1) end from public.learning_events e where e.course_key=p_course_key and e.created_at>=v_since),
  'top_errors', (select coalesce(jsonb_agg(jsonb_build_object('competency_key',x.competency_key,'errors',x.errors,'attempts',x.attempts) order by x.errors desc),'[]'::jsonb) from (select e.competency_key,count(*) filter(where e.is_correct=false) errors,count(*) filter(where e.is_correct is not null) attempts from public.learning_events e where e.course_key=p_course_key and e.created_at>=v_since group by e.competency_key having count(*) filter(where e.is_correct=false)>0 order by errors desc limit 12) x)
 ) into v_result;
 analytics:=v_result;return next;
end;$$;
revoke all on function public.get_admin_course_analytics(text,integer) from public;
grant execute on function public.get_admin_course_analytics(text,integer) to authenticated;

grant select on public.learning_events,public.skill_mastery,public.study_sessions,public.maintenance_reviews,public.challenge_attempts to authenticated;
-- Do NOT grant direct access to challenge_templates or platform_admins.
