(function(){
const bank={mixed:[
{tag:'Sémiologie',q:'Un patient dort trois heures sans fatigue et dit ne pas avoir besoin de davantage de sommeil. Quelle formulation est la plus précise ?',o:['Insomnie terminale','Diminution du besoin de sommeil','Hypersomnie','Restriction volontaire'],a:1,e:'La diminution du besoin de sommeil associe un sommeil nettement raccourci à l’absence de besoin compensatoire et de fatigue attendue.',wrong:{0:'Une insomnie implique une difficulté ou une plainte de sommeil : le sujet voudrait généralement dormir davantage ou ressentirait les conséquences du manque.',2:'L’hypersomnie désigne un sommeil excessif ou une somnolence accrue, soit l’inverse du phénomène décrit ici.',3:'Une restriction volontaire réduit le temps de sommeil par choix ou contrainte, sans démontrer une diminution du besoin physiologique de dormir.'},skill:'Sommeil · besoin vs durée'},
{tag:'Cours de pensée',q:'Quel élément distingue le mieux la fuite des idées d’une simple tachypsychie ?',o:['La vitesse seule','La multiplication des associations avec changement rapide de direction','Le volume sonore','La durée du discours'],a:1,e:'La tachypsychie décrit surtout l’accélération. La fuite des idées ajoute une mobilité associative marquée avec changements rapides de direction.',wrong:{0:'La vitesse seule définit plutôt la tachypsychie. Pour parler de fuite des idées, il faut aussi une modification de la direction associative.',2:'Le volume sonore concerne la prosodie ou la pression du discours, pas l’organisation associative de la pensée.',3:'Un discours long peut être circonstanciel, logorrhéique ou simplement détaillé ; sa durée ne suffit pas à caractériser une fuite des idées.'},skill:'Cours de pensée · vitesse vs direction'},
{tag:'Diagnostic',q:'Dans une dépression actuelle, quelle information a le plus de pouvoir pour rechercher une bipolarité ?',o:['L’intensité de la tristesse','Une période passée nettement limitée avec changement observable d’activation','Une anxiété actuelle','La présence d’insomnie'],a:1,e:'La polarité se reconstruit longitudinalement à partir d’épisodes distincts. Un antécédent d’activation épisodique est beaucoup plus discriminant que l’intensité de la dépression actuelle.',wrong:{0:'L’intensité dépressive n’est pas spécifique de la bipolarité et peut être sévère dans un trouble dépressif unipolaire.',2:'L’anxiété est fréquente dans plusieurs troubles de l’humeur et n’établit pas la polarité.',3:'L’insomnie est transdiagnostique. Sa présence seule ne distingue pas une dépression bipolaire d’une dépression unipolaire.'},skill:'Temporalité · reconstruction longitudinale'},
{tag:'Raisonnement',q:'Une nouvelle donnée contredit votre hypothèse principale. Quelle réponse est la plus robuste ?',o:['Ignorer la donnée','Reclasser les hypothèses et recalibrer la certitude','Changer automatiquement de diagnostic','Attendre la fin sans modifier le raisonnement'],a:1,e:'Un raisonnement clinique robuste met à jour la hiérarchie diagnostique sans passer d’une fermeture prématurée à une autre.',wrong:{0:'Ignorer une donnée contradictoire favorise le biais de confirmation.',2:'Changer automatiquement de diagnostic transforme une donnée nouvelle en conclusion prématurée. Il faut reclasser l’ensemble des hypothèses.',3:'Reporter toute mise à jour empêche le raisonnement bayésien clinique : la hiérarchie doit évoluer au fil du dossier.'},skill:'Raisonnement · flexibilité'},
{tag:'Psychométrie',q:'Une échelle de dépistage positive suffit-elle à poser un diagnostic bipolaire ?',o:['Oui','Seulement si le score est très élevé','Non, elle oriente l’évaluation mais ne remplace pas l’entretien diagnostique','Oui si répétée deux fois'],a:2,e:'Une échelle de dépistage estime un risque ou une probabilité clinique. Le diagnostic repose sur l’entretien, les critères, le retentissement et la reconstruction longitudinale.',wrong:{0:'Un résultat positif augmente la nécessité d’explorer, mais ne démontre pas à lui seul un trouble bipolaire.',1:'Même un score élevé ne transforme pas un outil de dépistage en instrument diagnostique.',3:'La répétition d’un outil de dépistage n’en change pas la fonction : elle ne remplace pas l’évaluation diagnostique.'},skill:'Psychométrie · dépistage vs diagnostic'}
]};
bank.semiology=[bank.mixed[0],bank.mixed[1]];bank.diagnostic=[bank.mixed[2],bank.mixed[3],bank.mixed[4]];bank.adaptive=bank.mixed;
let mode=new URLSearchParams(location.search).get('mode')||'mixed',i=0,selected=null,validated=false;const q=id=>document.getElementById(id);
function arr(){return bank[mode]||bank.mixed}function cur(){return arr()[i%arr().length]}
function draw(){const r=cur();q('quizProgress').textContent=(i+1)+' / '+arr().length;q('quizTag').textContent=r.tag;q('quizQuestion').textContent=r.q;q('quizOptions').innerHTML=r.o.map((x,n)=>`<button data-opt="${n}" style="padding:12px 13px;border:1px solid #dce5e2;background:#fff;border-radius:10px;text-align:left;cursor:pointer"><b style="color:#65777e;margin-right:8px">${String.fromCharCode(65+n)}</b>${x}</button>`).join('');q('quizFeedback').style.display='none';q('quizFeedback').innerHTML='';q('quizNext').textContent='Valider';selected=null;validated=false;document.querySelectorAll('[data-opt]').forEach(b=>b.onclick=()=>{if(validated)return;selected=Number(b.dataset.opt);document.querySelectorAll('[data-opt]').forEach(x=>{x.style.borderColor=x===b?'#3e9f90':'#dce5e2';x.style.background=x===b?'#edf7f4':'#fff'})})}
function feedback(full=false){if(selected===null&&!full)return;const r=cur(),ok=selected===r.a,box=q('quizFeedback');box.style.display='block';box.style.background=ok?'#edf7f3':'#fbf0ee';if(full&&selected===null){box.innerHTML=`<b>Point clé</b><br>${r.e}`;return}if(ok){box.innerHTML=`<b>✓ Bonne réponse.</b><br>${r.e}<div style="margin-top:8px;color:#607078"><b>À retenir :</b> ${r.skill}</div>`}else{box.innerHTML=`<b>Pourquoi cette réponse est fausse</b><br>${r.wrong?.[selected]||'Ce choix est compatible avec une partie du tableau, mais il n’explique pas le phénomène discriminant recherché ici.'}<div style="margin-top:9px;padding-top:9px;border-top:1px solid rgba(0,0,0,.08)"><b>Le détail qui change tout :</b> ${r.e}</div><div style="margin-top:7px;color:#607078"><b>À travailler :</b> ${r.skill}</div>`}}
function setMode(m){mode=m in bank?m:'mixed';i=0;document.querySelectorAll('[data-mode]').forEach(b=>b.classList.toggle('active',b.dataset.mode===mode));draw()}
document.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>setMode(b.dataset.mode));q('quizNext').onclick=()=>{if(!validated){if(selected===null)return;validated=true;feedback();q('quizNext').textContent=i===arr().length-1?'Recommencer':'Suivant'}else{i=(i+1)%arr().length;draw()}};q('quizExplain').onclick=()=>feedback(true);setMode(mode);
})();
