(function(){
const isEN=document.documentElement.lang==='en';
function addN3(){const grid=document.querySelector('.bl56-hub-grid');if(!grid||grid.querySelector('.v58-soon'))return;const a=document.createElement('article');a.className='bl56-level v58-soon';a.innerHTML=isEN?'<header><div><small>N3</small><h2>Treat</h2></div><span class="bl56-level-badge">CARE LAB</span></header><p>Build an integrated care plan: treatment, psychoeducation, rhythms, functioning and relapse prevention.</p><div class="bl56-level-missions"><button disabled>Integrated care<small>Coming soon</small></button><button disabled>Psychoeducation<small>Coming soon</small></button><button disabled>Relapse prevention<small>Coming soon</small></button></div>':'<header><div><small>N3</small><h2>Soigner</h2></div><span class="bl56-level-badge">CARE LAB</span></header><p>Construire une prise en charge intégrée : traitements, psychoéducation, rythmes, fonctionnement et prévention.</p><div class="bl56-level-missions"><button disabled>Prise en charge intégrée<small>Bientôt disponible</small></button><button disabled>Psychoéducation<small>Bientôt disponible</small></button><button disabled>Prévention des rechutes<small>Bientôt disponible</small></button></div>';grid.appendChild(a)}
function collapseCodex(){document.querySelectorAll('.unlock').forEach(u=>{if(u.dataset.v58done)return;u.dataset.v58done='1';const codex=u.querySelector('.codex');if(!codex)return;const b=document.createElement('button');b.type='button';b.className='v58-codex-toggle';b.textContent=isEN?'Open term sheet':'Voir la fiche-terme';b.addEventListener('click',()=>{u.classList.toggle('v58-open');b.textContent=u.classList.contains('v58-open')?(isEN?'Collapse term sheet':'Réduire la fiche'):(isEN?'Open term sheet':'Voir la fiche-terme')});u.insertBefore(b,codex)})}
function axoneButton(){if(document.querySelector('.v58-study-axone'))return;const b=document.createElement('button');b.type='button';b.className='v58-study-axone';b.setAttribute('aria-label',isEN?'Open Dr Axon':'Ouvrir Dr Axone');b.addEventListener('click',()=>document.querySelector('#bl56Axone')?.classList.add('show'));document.body.appendChild(b)}
function rename(){document.querySelectorAll('.bl56-course-head h1').forEach(h=>h.textContent='BipolarLab');const p=document.querySelector('.bl56-course-head p');if(p)p.textContent=isEN?'Semiology, diagnostic reasoning and care: a progressive, clinical and interactive pathway.':'Sémiologie, raisonnement diagnostique et prise en charge : un parcours progressif, clinique et interactif.';}
function init(){setTimeout(()=>{addN3();collapseCodex();axoneButton();rename()},0)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
new MutationObserver(()=>collapseCodex()).observe(document.documentElement,{subtree:true,childList:true});
})();
