(function(){
  const LANG_KEY='psylab_lang_v59', THEME_KEY='psylab_theme_v59';
  const savedLang=(localStorage.getItem(LANG_KEY)||document.documentElement.lang||'fr').toLowerCase().startsWith('en')?'en':'fr';
  const savedTheme=localStorage.getItem(THEME_KEY)||'auto';
  const media=window.matchMedia?.('(prefers-color-scheme: dark)');
  const statusMap={
    fr:{EXTERNE:'Externe',INTERNE:'Interne',R1:'Résident R1',R2:'Résident R2',R3:'Résident R3',R4:'Résident R4',ASSISTANT:'Assistant',PROFESSEUR:'Professeur'},
    en:{EXTERNE:'Extern',INTERNE:'Intern',R1:'Resident R1',R2:'Resident R2',R3:'Resident R3',R4:'Resident R4',ASSISTANT:'Assistant',PROFESSEUR:'Professor'}
  };
  const dict={
    fr:{home:'Accueil',labs:'Labs',maintenance:'Maintien',coat:'Le Vestiaire',profile:'Profil',search:'Rechercher un contenu, un Lab, une notion…',signin:'Se connecter',signup:'Créer un compte',email:'Adresse e-mail',password:'Mot de passe',welcome_back:'Bon retour.',resume_prompt:'Connectez-vous pour reprendre votre parcours.',platform_tag:'APPRENDRE · RAISONNER · PROGRESSER',forgot:'Mot de passe oublié ?',create_space:'Créer mon espace',pseudo:'Pseudonyme public',status:'Statut professionnel',cohort:'Promotion / groupe',privacy:'Votre e-mail reste privé. Votre photo et votre pseudonyme se règlent dans le profil.',or:'ou',google:'Continuer avec Google',apple:'Continuer avec Apple',complete_profile:'Compléter votre profil',complete_profile_sub:'Une dernière étape avant d’entrer dans PsyLab.',save_continue:'Enregistrer et continuer',resume:'Reprendre votre parcours',continue:'Continuer',my_labs:'Mes Labs',see_all:'Voir tous les Labs',coming:'Bientôt',coat_kicker:'TOUT LE MONDE VEUT',coat_title:'LA BLOUSE',coat_cta:'JE VEUX LA BLOUSE',current_holder:'Titulaire actuel',week_case:'Cas de la semaine',participants:'participants',maintenance_locked:'Se débloque lorsque vous terminez un Lab.',retention_due:'Révisions à distance disponibles',start:'Commencer',choose_lab:'Choisir un parcours',lab_desc:'Chaque Lab est un parcours autonome. Votre compte et votre progression restent communs à toute la plateforme.',available:'Disponible',open_lab:'Ouvrir le Lab',competition_weekly:'LA COMPÉTITION HEBDOMADAIRE',competition_intro:'Un dossier clinique par semaine. Une tentative classée. Le raisonnement compte davantage que la vitesse.',defend:'Défendre ma blouse →',want:'Je veux la blouse →',my_rank:'Votre rang',attempt:'Tentative',weekly_case:'Le dossier de la semaine',leaderboard:'Classement actuel',identity:'Informations du compte',save:'Enregistrer',logout:'Se déconnecter',photo:'Photo de profil',choose_photo:'Changer la photo',remove:'Retirer',language:'Langue',public_photo:'Afficher ma photo dans les classements',preferences:'Préférences',account:'Compte',progress:'Progression',awards:'Distinctions',notifications:'Notifications',maintenance_title:'Maintien',maintenance_sub:'Réviser à distance ce que vous avez déjà acquis.',maintenance_explain:'Le Maintien se débloque automatiquement lorsqu’un Lab est terminé. Il réactive ensuite les notions à J+7, J+30, J+90 puis à intervalles espacés.',no_lab_finished:'Aucun Lab terminé pour le moment.'},
    en:{home:'Home',labs:'Labs',maintenance:'Retention',coat:'Locker Room',profile:'Profile',search:'Search a topic, a Lab, a concept…',signin:'Sign in',signup:'Create account',email:'Email address',password:'Password',welcome_back:'Welcome back.',resume_prompt:'Sign in to resume your learning.',platform_tag:'LEARN · REASON · PROGRESS',forgot:'Forgot password?',create_space:'Create my space',pseudo:'Public nickname',status:'Professional status',cohort:'Cohort / group',privacy:'Your email stays private. Photo and public nickname are managed in your profile.',or:'or',google:'Continue with Google',apple:'Continue with Apple',complete_profile:'Complete your profile',complete_profile_sub:'One last step before entering PsyLab.',save_continue:'Save and continue',resume:'Resume your learning',continue:'Continue',my_labs:'My Labs',see_all:'View all Labs',coming:'Coming soon',coat_kicker:'EVERYONE WANTS',coat_title:'THE WHITE COAT',coat_cta:'I WANT THE COAT',current_holder:'Current title holder',week_case:'Case of the week',participants:'participants',maintenance_locked:'Unlocks after you complete a Lab.',retention_due:'Spaced-review sessions available',start:'Start',choose_lab:'Choose a learning path',lab_desc:'Each Lab is a standalone course. Your account and progress stay shared across PsyLab.',available:'Available',open_lab:'Open Lab',competition_weekly:'THE WEEKLY COMPETITION',competition_intro:'One clinical case each week. One ranked attempt. Reasoning matters more than speed.',defend:'Defend my coat →',want:'I want the coat →',my_rank:'Your rank',attempt:'Attempt',weekly_case:'This week’s case',leaderboard:'Current leaderboard',identity:'Account information',save:'Save',logout:'Sign out',photo:'Profile photo',choose_photo:'Change photo',remove:'Remove',language:'Language',public_photo:'Show my photo in rankings',preferences:'Preferences',account:'Account',progress:'Progress',awards:'Awards',notifications:'Notifications',maintenance_title:'Retention',maintenance_sub:'Revisit what you have already learned at increasing intervals.',maintenance_explain:'Retention unlocks automatically after you complete a Lab. It then brings key concepts back at day 7, day 30, day 90 and later spaced intervals.',no_lab_finished:'No completed Lab yet.'}
  };
  function lang(){const v=String(localStorage.getItem(LANG_KEY)||savedLang||'fr').toLowerCase();return v.startsWith('en')?'en':'fr'}
  function resolvedTheme(){const t=localStorage.getItem(THEME_KEY)||savedTheme;return t==='auto'?(media?.matches?'dark':'light'):t}
  function applyTheme(){document.documentElement.dataset.theme=resolvedTheme();document.documentElement.dataset.themePreference=localStorage.getItem(THEME_KEY)||savedTheme;document.querySelectorAll('[data-theme-icon]').forEach(x=>x.textContent=resolvedTheme()==='dark'?'☾':'☀')}
  function tr(k){return dict[lang()]?.[k]||dict.fr[k]||k}
  function statusLabel(v,l=lang()){return statusMap[l]?.[v]||statusMap.fr[v]||v||''}
  function applyText(){document.documentElement.lang=lang();document.querySelectorAll('[data-i18n]').forEach(el=>{const k=el.dataset.i18n;if(dict[lang()]?.[k]!=null)el.textContent=dict[lang()][k]});document.querySelectorAll('[data-i18n-placeholder]').forEach(el=>el.placeholder=tr(el.dataset.i18nPlaceholder));document.querySelectorAll('[data-lang-fr]').forEach(el=>el.classList.toggle('active',lang()==='fr'));document.querySelectorAll('[data-lang-en]').forEach(el=>el.classList.toggle('active',lang()==='en'));document.querySelectorAll('[data-status-option]').forEach(el=>{el.textContent=statusLabel(el.value)})}
  function setLang(v){v=v==='en'?'en':'fr';localStorage.setItem(LANG_KEY,v);const ctx=window.PSYLAB_V60_CONTEXT||window.PSYLAB_V59_CONTEXT||window.PSYLAB_V57_PAGE;try{ctx?.client?.from('profiles').update({preferred_language:v}).eq('id',ctx.user.id).then(()=>{});}catch(_){} location.reload()}
  function cycleTheme(){const pref=localStorage.getItem(THEME_KEY)||'auto';const next=pref==='auto'?'light':pref==='light'?'dark':'auto';localStorage.setItem(THEME_KEY,next);applyTheme();document.dispatchEvent(new CustomEvent('psylab:v60-theme',{detail:{theme:resolvedTheme(),preference:next}}))}
  function courseHref(c){return lang()==='en'?(c.href_en||c.href):c.href}
  function bind(){document.querySelectorAll('[data-lang-fr]').forEach(b=>b.onclick=()=>setLang('fr'));document.querySelectorAll('[data-lang-en]').forEach(b=>b.onclick=()=>setLang('en'));document.querySelectorAll('[data-theme-toggle]').forEach(b=>b.onclick=cycleTheme);applyText();applyTheme()}
  const api={lang,tr,setLang,applyText,applyTheme,cycleTheme,courseHref,resolvedTheme,statusLabel,dict,statusMap};
  window.PsyLabV60=api;window.PsyLabV59=api;
  applyTheme();if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',bind);else bind();media?.addEventListener?.('change',()=>{if((localStorage.getItem(THEME_KEY)||'auto')==='auto')applyTheme()});
})();
