(function(){
const isEN=document.documentElement.lang==='en';
function text(el){return (el?.textContent||'').replace(/\s+/g,' ').trim()}
function explainMain(btn){const card=btn.closest('.case-card');if(!card||!btn.classList.contains('wrong'))return;const q=btn.dataset.q,fb=document.getElementById('mainfb-'+q),correct=card.querySelector(`.choice[data-kind="main"][data-i="${card.dataset.answer}"]`),nuance=card.querySelector(`.choice[data-kind="nuance"][data-i="${card.dataset.nuance}"]`),compare=card.querySelector('.codex-grid>div:nth-child(2) p'),selected=text(btn).replace(/^[A-D]\s*/,'');const target=card.dataset.term||text(correct),key=text(nuance).replace(/^\d\s*/,'');let why=`Vous avez choisi « ${selected} ». Ce choix appartient au même voisinage clinique, mais il ne décrit pas le phénomène central isolé par la scène.`;if(compare&&text(compare).toLowerCase().includes(selected.toLowerCase().split(' ')[0]))why=text(compare);fb.innerHTML=isEN?`<b>Why this answer is not the best choice</b><div class="v57-answer-explain">You selected “${selected}”. This option is clinically related, but it does not describe the central phenomenon isolated by the vignette.</div><div class="v57-answer-key"><b>Discriminating clue:</b> ${key||'return to the feature that distinguishes the structure of the phenomenon.'}</div><span class="v57-answer-tag">Key concept · ${target}</span>`:`<b>Pourquoi cette réponse est fausse</b><div class="v57-answer-explain">${why}</div><div class="v57-answer-key"><b>Le détail discriminant :</b> ${key||'reprenez le fait qui distingue la structure du phénomène.'}</div><span class="v57-answer-tag">À retenir · ${target}</span>`}
function explainCorrect(btn){const card=btn.closest('.case-card');if(!card||!btn.classList.contains('correct'))return;const q=btn.dataset.q,fb=document.getElementById('mainfb-'+q),nuance=card.querySelector(`.choice[data-kind="nuance"][data-i="${card.dataset.nuance}"]`),key=text(nuance).replace(/^\d\s*/,'');if(fb&&!fb.querySelector('.v57-answer-key'))fb.insertAdjacentHTML('beforeend',isEN?`<div class="v57-answer-key"><b>Why:</b> ${key||'the vignette matches the defining structure of this phenomenon.'}</div>`:`<div class="v57-answer-key"><b>Pourquoi :</b> ${key||'la scène correspond précisément à la structure de ce phénomène.'}</div>`)}
document.addEventListener('click',e=>{const b=e.target.closest('.choice[data-kind="main"]');if(!b)return;setTimeout(()=>{explainMain(b);explainCorrect(b)},0)});
// Make the course hub the default surface and remove legacy visual clutter from navigation.
document.addEventListener('DOMContentLoaded',()=>{document.body.classList.add('v57-bipolar');const old=document.querySelector('nav.nav');if(old)old.setAttribute('aria-hidden','true')});
})();
